### ISSUE TITLE
yum / apt repository for aerospike package based installation

### ISSUE THREAD

**Issue by vkhatri** [aerospike/aerospike-server#100]
Hello! I was able to get `aerospike` up and running in no time following the documented steps. But, i was thinking that it would be really great if we can have `yum/apt` repository for `Package` based installation, instead of downloading an archive and executing `./asinstall`.

I am interested to know if there is any plan to introduce `yum/apt` repository in the future or any time sooner.

thanks!

**Comment by paulhovey** [comment]
+1, apt-get aerospike would be awesome!

**Comment by Chyzwar** [comment]
imo snappy should be way to go for any Ubuntu based distro. Snappy benefits are huge. You will no longer need to have different versions per release 12/14/16 etc
http://www.pcworld.com/article/2942267/why-ubuntu-plans-to-replace-traditional-linux-packages-with-something-better.html
``
sudo snap install aerospike
``

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
