### ISSUE TITLE
amc debian and ubuntu url points to same .deb file

### ISSUE THREAD

**Issue by vkhatri** [aerospike/aerospike-server#101]
hello! URL `http://www.aerospike.com/download/amc/3.6.3/artifact/ubuntu12` and `http://www.aerospike.com/download/amc/3.6.3/artifact/debian6` points to same `.deb` file -
 `http://www.aerospike.com/artifacts/aerospike-amc-community/3.6.3/aerospike-amc-community-3.6.3.all.x86_64.deb`.

Could you please confirm whether package build is now common for `debian` platform family os? it seems like the case by looking at the file name `aerospike-amc-community-3.6.3.all.x86_64.deb`.

**Comment by wchu-citrusleaf** [comment]
This is correct.
