### ISSUE TITLE
SIGSEGV crashed when get namespace not exist.

### ISSUE THREAD

**Issue by absolute8511** [aerospike/aerospike-server#105]
The client tried twice requests with the non-exist namespace and the server is down. Log as below:

Nov 17 2015 03:37:40 GMT: WARNING (demarshal): (thr_demarshal.c::570) Can't get namespace from AS_MSG (peeked 83 bytes) ~~ Using default thr_demarshal arena.
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::160) SIGSEGV received, aborting Aerospike Community Edition build 3.5.15
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: found 7 frames
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 0: /opt/aerospike/bin/asd(as_sig_handle_segv+0x59) [0x46f718]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 1: /lib64/libc.so.6() [0x3dc08326a0]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 2: /opt/aerospike/bin/asd(as_msg_peek_data_in_memory+0x32) [0x4676e2]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 3: /opt/aerospike/bin/asd(thr_tsvc_process_or_enqueue+0x29) [0x4c027f]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 4: /opt/aerospike/bin/asd(thr_demarshal+0x38f) [0x48416a]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 5: /lib64/libpthread.so.0() [0x3dc0c07a51]
Nov 17 2015 03:37:40 GMT: WARNING (as): (signal.c::162) stacktrace: frame 6: /lib64/libc.so.6(clone+0x6d) [0x3dc08e893d]

**Comment by wchu-citrusleaf** [comment]
What client was used in this case?

**Comment by absolute8511** [comment]
using Java client，maybe caused by `Key key = new Key(null, "demo", "putgetkey");` with null namespace?

**Comment by psi-mankoski** [comment]
Hello. Are you still seeing this problem? What version of the Java client are you using? Have you tried the latest Aerospike Server CE release (3.7.1)?

So far, we have been unable to trigger a crash with a simple Java client app. (using Java client version 3.1.5) based upon the line you sent: [The commented-out lines show various different test cases we attempted.]

import com.aerospike.client.*;

public class test {
	static public void main(String args[]) {
		AerospikeClient client = new AerospikeClient("127.0.0.1", 3000);

//		Key key = new Key("test", "", "JK1");
//		Key key = new Key(null, "", "JK1");
//		Key key = new Key(null, null, "JK1");
		Key key = new Key(null, null, "");
//		Bin bin = new Bin("B1", "V1");
		Bin bin = new Bin(null, "");

		for (int i = 0; i < 10; i++) {
			System.out.println("Test[" + i + "]:");
			try {
				// Write a record
				client.put(null, key, bin);
			} catch (AerospikeException ex) {
				System.out.println("Caught exception: " + ex);
			}
		}
		
		// Read a record
		Record record = client.get(null, key);

		client.close();
	}
}

**Comment by absolute8511** [comment]
We crashed while using the build 3.5.15 and we did not try the 3.7.1 yet. I will see if any problem with the 
`Key key = new Key(null, "demo", "putgetkey");` or `Key key = new Key("", "demo", "putgetkey");`

**Comment by absolute8511** [comment]
issue still exist and we do the secondary index query without namespace.
```
Feb 22 2016 07:08:11 GMT: WARNING (demarshal): (thr_demarshal.c::610) Can't get namespace from AS_MSG (peeked 120 bytes) ~~ Using default thr_demarshal arena.
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::161) SIGSEGV received, aborting Aerospike Community Edition build 3.7.1 os el6
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: found 7 frames
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 0: /usr/bin/asd(as_sig_handle_segv+0x62) [0x48c607]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 1: /lib64/libc.so.6() [0x3dc08326a0]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 2: /usr/bin/asd(as_msg_peek_data_in_memory+0x32) [0x485f95]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 3: /usr/bin/asd(thr_tsvc_process_or_enqueue+0x29) [0x4da32e]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 4: /usr/bin/asd(thr_demarshal+0xc5f) [0x4a2f81]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 5: /lib64/libpthread.so.0() [0x3dc0c07a51]
Feb 22 2016 07:08:11 GMT: WARNING (as): (signal.c::163) stacktrace: frame 6: /lib64/libc.so.6(clone+0x6d) [0x3dc08e893d]
```

**Comment by psi-mankoski** [comment]
Hello. Can you still cause this crash? We tried various ways (the latest Java Client, v3.2.2, as well as the much older v3.1.5) against the latest server (v3.8.2, as well as v3.5.15) using variations of the program below to do a secondary index query without sending the namespace, but the worst we saw was WARNING logs, no crashes.

If you can send a simple test app. that causes the crash for you, that would be very helpful. Thanks!

```Java
import com.aerospike.client.*;
import com.aerospike.client.query.*;

public class test {
	static public void main(String args[]) {
		System.out.println("Opening client connection....");
		
		AerospikeClient client = new AerospikeClient("127.0.0.1", 3000);

		Statement stmt = new Statement();

//		stmt.setNamespace("test");
//		stmt.setNamespace("t2");
//		stmt.setNamespace("");
//		stmt.setNamespace(null);
		stmt.setSetName("demo");
		stmt.setBinNames("B0");

//		stmt.setFilters(Filter.equal("B0", 0));
		stmt.setFilters(Filter.range("B0", 0, 1));

		System.out.println("Issuing query w/o namespace....");

		RecordSet rs = client.query(null, stmt);

		System.out.println("Processing results....");

		try {
			while (rs.next()) {
				System.out.println("Got one!!!");
				Key key = rs.getKey();
				Record record = rs.getRecord();
			}
		} finally {
			rs.close();
		}

		System.out.println("Closing client connection....");

		client.close();
	}
}
```

**Comment by kaniini** [comment]
For what it's worth, this appears to be an overrun in `as_msg_field_get_next()` which [does no bounds checking](https://github.com/aerospike/aerospike-server/blob/1538bd512f9ec264232c596bcf769011ad20853d/as/include/base/proto.h#L385-L429).  This means this is probably a security bug as a malformed packet may be able to crash the server.

**Comment by psi-mankoski** [comment]
Good observation! Can you either create, or else describe in detail so that I can create, the exact sort of packet that would cause this overrun? Thanks for your help.

**Comment by kaniini** [comment]
A packet where `n_fields` is larger than the actual number of fields is likely the culprit.

**Comment by psi-mankoski** [comment]
Thanks ~~ I'll investigate further and let you all know what I find....

**Comment by wchu-citrusleaf** [comment]
We've fixed a few bound check issues through the past year's release. Recommend retrying.

Also, Aerospike MUST be run within secure network environments with trusted clients only to ensure data safety.
