### ISSUE TITLE
ascli (aerospike 3.6.x) does not pass parameters to UDFs 

### ISSUE THREAD

**Issue by szhem** [aerospike/aerospike-server#107]
Here is how to reproduce 

1\. Create a sample UDF that accepts parameters

    $ cat <<END > ascli_params.lua
    function reflect(rec, param)
        return param                                                                  
    end
    END

2\. Register UDF

    $ ascli udf-put ./ascli_params.lua

3\. Invoke UDF by means of ascli

    $ ascli udf-record-apply test test 1 'ascli_params' 'reflect' 'param'
    $ null

4\. Invoke UDF by means of aql

    $ aql -c "execute ascli_params.reflect('param') on test.test where pk = 1"
    +---------+
    | reflect |
    +---------+
    | "param" |
    +---------+
    1 row in set (0.001 secs)

5\. Invoke UDF by means of ascli from version 3.3.20 (3.4.x, 3.5.x fail with coredump when invoking against asd 3.6.4)

    $ ./ascli udf-record-apply test test 1 'ascli_params' 'reflect' 'param'
    "param"

6\. And here are tcpdumps of ascli 3.6.4 and ascli 3.3.20 correspondingly 

**ascli 3.6.4**

    $ sudo tcpdump port 3000 -i lo -s 0 -X | grep -C 1 -E 'test|ascli_params|reflect|param'
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
	0x0300:  2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f  ////////////////
	0x0310:  2f2f 2f2f 2f2f 383d 3b74 6573 743a 2f2f  //////8=;test://
	0x0320:  2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f  ////////////////
    --
	0x0880:  4141 4141 4141 4141 4141 4141 4141 3d3b  AAAAAAAAAAAAAA=;
	0x0890:  7465 7374 3a41 4141 4141 4141 4141 4141  test:AAAAAAAAAAA
	0x08a0:  4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
    --
	0x0040:  0000 0000 0000 0000 0000 0000 0000 0006  ................
	0x0050:  0000 0000 0005 0074 6573 7400 0000 0501  .......test.....
	0x0060:  7465 7374 0000 0015 04f5 1ac0 7799 7064  test........w.pd
	0x0070:  e036 1140 73f6 1940 d3cc ad2d 7900 0000  .6.@s..@...-y...
	0x0080:  0d1e 6173 636c 695f 7061 7261 6d73 0000  ..ascli_params..
	0x0090:  0008 1f72 6566 6c65 6374 0000 0001 20    ...reflect.....

**ascli 3.3.20**

    $ sudo tcpdump port 3000 -i lo -s 0 -X | grep -C 1 -E 'test|ascli_params|reflect|param'
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
	0x0300:  2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f  ////////////////
	0x0310:  2f2f 2f2f 2f2f 383d 3b74 6573 743a 2f2f  //////8=;test://
	0x0320:  2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f 2f2f  ////////////////
    --
	0x0880:  4141 4141 4141 4141 4141 4141 4141 3d3b  AAAAAAAAAAAAAA=;
	0x0890:  7465 7374 3a41 4141 4141 4141 4141 4141  test:AAAAAAAAAAA
	0x08a0:  4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
    --
	0x0040:  0000 0000 0000 0000 0000 0000 0000 0006  ................
	0x0050:  0000 0000 0005 0074 6573 7400 0000 0501  .......test.....
	0x0060:  7465 7374 0000 000d 1e61 7363 6c69 5f70  test.....ascli_p
	0x0070:  6172 616d 7300 0000 081f 7265 666c 6563  arams.....reflec
	0x0080:  7400 0000 0920 91a6 0370 6172 616d 0000  t........param..
	0x0090:  0002 0203                                ....
    --
	0x0050:  0001 0000 0010 0103 0007 5355 4343 4553  ..........SUCCES
	0x0060:  5370 6172 616d                           Sparam

As you can see there is no **param** parameter on the wire when using **ascli 3.6.4**

**Comment by maxim-ky** [comment]
Hello guys!
What's going on here? I have the same issue :(

**Comment by wchu-citrusleaf** [comment]
Recommend using AQL as a command line tool. ascli related issues may not be fixed quickly.

**Comment by wchu-citrusleaf** [comment]
Have decided to obsolete ascli.
