### ISSUE TITLE
doc typos

### ISSUE THREAD

**Issue by glycerine** [aerospike/aerospike-server#108]
1. missing a letter 'o'

> Technology -> User-defined functions -> Why Lua ->
> "Aerospike creates a queue of Lua contexts - no more than on per thread, per registered UDFs - greatly reducing latency and increasing performance."

Likely: the phrase "no more than _on_ per thread" should(?) be "no more than _one_ per thread".  I say should(?) because the resulting sentence then makes gramatical sense, although it still lacks semantic meaning: what does it mean to have one "queue of contexts" per thread, per registered UDFs (and why is UDFs plural)? The sentence is confusing and it should be re-written so that its meaning is clear.

2nd. Re-use of a figure showing replication when describing a non-replicated situation.

http://www.aerospike.com/docs/architecture/data-distribution.html

> Technology -> Distribution -> How Data is Replicated/Synchronized locally -> An Aerospike Cluster with No Replication

The same figure image is used for the "no replication" description as for the "replication" description. Instead the "no replication" situation should have it's own figure which does not exhibit replication at all.

![image](https://cloud.githubusercontent.com/assets/445247/11325977/2a343146-9111-11e5-8062-58783966477e.png)

3rd. It looks like you have some cross-site scripting hacks present on your website. The Recent Posts side-bar links to complete nonsense.From the analysts report page (http://www.aerospike.com/analyst-reports/), the side bar links to garbage content present on the Aerospike site, shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/445247/11326028/a54a486a-9112-11e5-838c-05ab154bdb4d.png)

**Comment by MichaelDiep** [comment]
Thank you, this has been updated.
