### ISSUE TITLE
Provide Ruby client

### ISSUE THREAD

**Issue by jacek99** [aerospike/aerospike-server#11]
Like many shops, we are using Cucumber BDDs for integration testing of our application.

That means our Ruby Cucumber steps need to be able to interact with Aerospike, at least for basic stuff like truncating a namespace between every test.

it would be great if you could provide at least a basic Ruby driver, otherwise integration with Cucumber (which is very common in any Agile / DevOp shop) is impossible.

**Comment by wchu-citrusleaf** [comment]
Ruby client is available. 
http://www.aerospike.com/download/client/ruby
