### ISSUE TITLE
generation in index and aggr is not matched with the generation in record.

### ISSUE THREAD

**Issue by absolute8511** [aerospike/aerospike-server#110]
In the `as_index` struct the generation is `uint16_t`,
in the aggr.c the function `query_record_gen` returned the `uint16_t`,
in the ldt_record.c function `ldt_record_gen` returned the `uint16_t`,

however it is `uint32_t` in both `struct drv_ssd_block_s` and `drv_kv_block_s`, 
in proto.h the `struct as_msg_s` is also `uint32_t`.

I think there is something wrong with this. 
The problem is found while using the atomic add for integer bin, I got the wrong generation after the integer bin increased over max of uint16_t.

**Comment by wchu-citrusleaf** [comment]
The uint16_t in index is the effective size. When generation goes beyond uint16_t, the system should wrap to 1.
Can you elaborate what you observe as "wrong generation"?

Thanks.

**Comment by absolute8511** [comment]
The system wrap to 1 means the generation in the index would be different from ssd_block.  Is it ok in the aerospike system?  Or is it designed to wrap from uint16_t?  If so, why the uint32_t is used in the ssd_block and in the proto `as_msg_s`.

I think It can be wrong while resolving the duplications during migration or cold startup. Could you please give some details to explain how to handle the mismatch generation between index and ssd_block in the system? 

Thanks.

**Comment by wchu-citrusleaf** [comment]
On any write, the generation from the index will be used to write to storage (ssd_block) or sent on wire (as_msg_s), so they will all be in sync. The extra 2 bytes in ssd_block and as_msg_s are (overzealous) forward-looking sizing to accommodate more generation counts. Currently they will always be empty.

Thanks.

**Comment by absolute8511** [comment]
OK, got it. Thanks again.
