### ISSUE TITLE
Hybrid storage with index in memory while data in disk file

### ISSUE THREAD

**Issue by thekiki** [aerospike/aerospike-server#113]
When I setup a dev/test env for Aerospike server, I check Aerospike document and found "Recipe for a HDD Storage Engine with Data in Memory" chapter.

I tried to set "data-in-memory" to false and everything works fine by now. But I am not quite sure what's going on there. Is this "index in memory + data in disk file" setup OK for a non-production environment?

**Comment by wchu-citrusleaf** [comment]
"index in memory + data in disk file" is a functional setup, but absolutely not recommended due to read performance of HDD.
