### ISSUE TITLE
Feature Request: Alias

### ISSUE THREAD

**Issue by oldmantaiter** [aerospike/aerospike-server#114]
Use case: Assign multiple keys pointing to the same data to avoid multiple lookups when doing a key mapping

Wondering if this would be as easy as assigning the same "pointer" to the area in storage that the primary key has.

I will look into the code, but was also wondering if there is an area where I could be directed to start investigating.

**Comment by oldmantaiter** [comment]
Just realized this is a lot like the secondary index, so I'll take a bit of a look into that and see if that adequately covers my use case.

**Comment by tfaulkes** [comment]
Hi,

This may be able to be done via a secondary index as you say, depending on the use case. We do have many clients that have this exact scenario, and they have a master record which contains the data and other records which point to this master record to solve the "multiple key" problem. Yes, this results in multiple look-ups, but they're very quick lookups and this technique tends to make code quicker and cleaner.

If you want to discuss your particular use-case, please feel free to drop an e-mail to sa@aerospike.com and we will be happy to help.

Thanks,

Tim Faulkes
Solutions Architect,
Aerospike
