### ISSUE TITLE
Unstable cluster after deleting sets

### ISSUE THREAD

**Issue by dhanasekaran1980** [aerospike/aerospike-server#115]
Hi,
I was using aerospike 3.6.3 two node cluster.

There were around 600+ unwanted sets lying around. Hence issued below command on both the nodes in a loop.  Issued the commands on both the nodes almost simultaneously.

asinfo -v "set-config:context=namespace;id=mynamespace;set=mysetname;set-delete=true;"

After this the commands got completed, I have witnessed unexpected behaviours in the cluster.
Couple of hours after delete event, one of the nodes went down abruptly without any errors in log.

After starting the node, the load went high with cpu usage 1100% on both the nodes and the cluster was unstable for almost 1 to 2 hrs.  Every time I restart node for some reason, the load get shooted up making the cluster unstable.

Yesterday I have upgraded to 3.7.3 and restarted nodes one by one.  As expected the cpu usage shoots up to 1000% + and settled down after 5 hours.  

Update 1: I have seen migration percent kept increasing slowly.
 from asmonitor stats,  "migrate_tx_objs" value in thousands.  I have seen this value coming down very slowly. This is now zero (0)

Kindly look into this issue.

**Comment by wchu-citrusleaf** [comment]
Please use the Aerospike forum https://discuss.aerospike.com/ for discussions with the community on deployment related observations.
