### ISSUE TITLE
RAM cache for SSD-based namespaces

### ISSUE THREAD

**Issue by br1985** [aerospike/aerospike-server#116]
We're in progress of migrating our main data set from Cassandra to Aerospike.

While overall Aerospike fits our needs much better, Cassandra had one feature that Aerospike is really missing. It can cache hot records in server memory. In our scenario even small cache (a few GBs per node) can get a hit ratio of 95% greatly reducing drives overload (that's our current bottleneck).

Are there any plans to add such feature to Aerospike? Or maybe there's some other mechanism that we sould consider?

I'm aware that we can put whole dataset in memory, but that's whould be inpractical in our case – SSDs are still way cheaper than RAM.

I'm also aware that we can create a second (RAM-only) namespace for cache and build cache logic in our app (there's a great chance will end up with this), but it has a few drawbacks comparing to build-in solutions (like Cassandra's row cache). Firstly, it will introduce extra latency for cold records (query cache first, then query real set). Secondy, it will require some delicate logic for cache invalidation and the like. Lastly, it will complicate architecture of our services (one component that is now strictly read-only will now make writes too – that's OK, but annoying and harder to maintain, monitor, diagnose etc...).

I believe one case in not very unique and Aerospike will greatly benefit from adding such feature in some future release.

EDIT: I'm talking (mostly) about caching reads (we do mostly reading). However, write cache would be nice too. If Aerospike could cache updated records in memory (a few minutes?) without flushing them to disk almost immediately that would save lots of SSD bandwidth in (e.g. our) case of updating same records over and over again (only a little percent of your users is active at any given moment). Of course, that can lead to lost updates in case of any failure, but we can live with that (while we can't live with frequent 'Device overload' errors).

**Comment by kportertx** [comment]
> However, write cache would be nice too.

There is a [write cache](http://www.aerospike.com/docs/reference/configuration#post-write-queue).

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
