### ISSUE TITLE
All data(stored on device) lost after upgrading from 3.7.1 to 3.7.3

### ISSUE THREAD

**Issue by felipejfc** [aerospike/aerospike-server#117]
Hi, I have a aerospike server running on a ec2 machine with one namespace configured as following:

namespace x {
	memory-size 60G
	default-ttl 0
	storage-engine device {
		device /dev/xvdf
		scheduler-mode noop
		write-block-size 128K
	}
}

It is a setup with only one machine, today I upgraded the aerospike server and tools following this steps:

```
stop aerospike service, then

# If upgrading without removing the older package
$ sudo rpm -Uvh aerospike-server-<EDITION>-<VERSION>.el6.x86_64.rpm 
$ sudo rpm -Uvh aerospike-tools-<EDITION>-<VERSION>.el6.x86_64.rpm

start aerospike service
```

And when the server came back online it had no more data on my namespace...

Was this behavior expected? Why have I lost my data if I'm using persistence?

P.S. One last observation, UDFs and Index definitions are intact

**Comment by wchu-citrusleaf** [comment]
Looking through the aerospike.log may give you more clues on the setup. You may want to seek the help of the community users at Aerospike's forum https://discuss.aerospike.com/
