### ISSUE TITLE
Can not build on Ubuntu 18.04

### ISSUE THREAD

**Issue by trungthanhnt** [aerospike/aerospike-server#12]
We can not build aerospike from source. Please submit the latest source code here. 
Thank you

**Comment by psi-mankoski** [comment]
Hello. The current Aerospike Server CE 4.6.0.2 source builds fine for us under Ubuntu 18.04.
Some questions:
1). Have you made sure to pull the submodules? ("git submodule update --init")?
2). Have you checked that you have installed all of the tool chain and library dependencies listed in the "README.md"?
3). If it still doesn't build for you, could you please send a detailed build log showing the commands used and the failure?
Thanks.

**Comment by Junus** [comment]
Hi @psi-mankoski,
I'm getting error while I'm trying to do `make tar` or `make deb`. Could you help me with that

make -C pkg/tar EDITION=community
make[1]: Entering directory '/FOLDER/aerospike-server/pkg/tar'
install -pm 755 -Dd /FOLDER/aerospike-server/pkg/dist/BUILD/aerospike-server
install -pm 644 -D /FOLDER/aerospike-server/pkg/tar/README /FOLDER/aerospike-server/pkg/dist/BUILD/aerospike-server/README
install -pm 644 -D ../../LICENSE /FOLDER/aerospike-server/pkg/dist/BUILD/aerospike-server/LICENSE
install -pm 755 -Dd /FOLDER/aerospike-server/pkg/dist/BUILD/aerospike-server/bin
install -pm 755 -D ../../target/Linux-x86_64/bin/asd /FOLDER/aerospike-server/pkg/dist/BUILD/aerospike-server/bin/asd
install: cannot stat '../../target/Linux-x86_64/bin/asd': No such file or directory
Makefile:20: recipe for target 'dist' failed
make[1]: *** [dist] Error 1
make[1]: Leaving directory '/home/junus/github/aerospike-server/pkg/tar'
Makefile:128: recipe for target 'tar' failed
make: *** [tar] Error 2

**Comment by psi-mankoski** [comment]
Hello. Did you do a "make" (with no arguments) first? The "make tar" / "make deb" / etc., targets are just packaging options, and they all only work after the basic "make" has completed successfully. It seems the "No such file..." error on the "bin/asd" executable means the basic build is not complete. If you encounter any errors doing that initial "make", please send them and I'll recommend how to proceed. Thanks.

**Comment by Junus** [comment]
> Hello. Did you do a "make" (with no arguments) first? The "make tar" / "make deb" / etc., targets are just packaging options, and they all only work after the basic "make" has completed successfully. It seems the "No such file..." error on the "bin/asd" executable means the basic build is not complete. If you encounter any errors doing that initial "make", please send them and I'll recommend how to proceed. Thanks.

Thanks, @psi-mankoski you were right, now everything is working

**Comment by psi-mankoski** [comment]
OK ~~ Glad it's working for you!
