### ISSUE TITLE
Provide way to easily truncate all data in set or namespace

### ISSUE THREAD

**Issue by jacek99** [aerospike/aerospike-server#12]
For doing integration testing, it is imperative to clean the DB before every test and start with a clean set.

This is extremely painful in Aerospike, since there is no simple TRUNCATE server command to delete the data in an entire set.

Doing the approach recommended by Aerospike:
https://github.com/aerospike/delete-set

will most likely be quite slow, as between every integration test BDD we will need to scan and delete, instead of a simple TRUNCATE, like on every other NoSQL or SQL platform.

**Comment by seenickcode** [comment]
+1

**Comment by nnaoumov** [comment]
+1

**Comment by m4grio** [comment]
+1

**Comment by lion-simba** [comment]
+1

**Comment by MaxJust** [comment]
+1

**Comment by b-a-t** [comment]
+2

**Comment by evyatar-via** [comment]
+1

**Comment by blitzprog** [comment]
+1

**Comment by jumping** [comment]
+1

**Comment by cqcwillard** [comment]
This feature is absolutely essential to development, why has this been closed with no resolution?  This prevents dynamic sets from being used at all.  I'm currently in a situation where a developer chose to create dynamic sets, and I now have no way to delete all of the indexes added to these sets minus copying and pasting each set name individually.

I've tried removing the shared memory locations, removing the .dat file and re-creating it, and restarting the server which have all failed.

**Comment by zorino** [comment]
+1

**Comment by sunlibin** [comment]
+1

2016-03-09 8:59 GMT+08:00 Maxime Déraspe <notifications@github.com>:

**Comment by lucasmartins** [comment]
+1

**Comment by maZahaca** [comment]
+1

**Comment by pedrodevoto** [comment]
+1

**Comment by wchu-citrusleaf** [comment]
Release 3.12 now supports namespace/set truncation based on last-update-time.

**Comment by bbulkow** [comment]
As of Aerospike 3.12, which was released in March 2017, the feature of deleting all data in a set or namespace is now supported in the database.

Please see the following documentation:
http://www.aerospike.com/docs/reference/info#truncate

Which provides the command line command that looks like:
asinfo truncate:namespace=<namespace name>;set=<set name>;lut=<time>

It can also be truncated from the client APIs, here is the java documentation:
http://www.aerospike.com/apidocs/java/com/aerospike/client/AerospikeClient.html
and scroll down to the "truncate" method.

Please note that this feature can, optionally, take a time specification. This allows you to delete records, then start inserting new records. As timestamps are used, please make certain your server clocks are well synchronized.

**Comment by mhareesh** [comment]
Hi 
I am getting error when truncate command(truncate:namespace=x;set=y;)  using asinfo 
the below error is getting logged in aerospike log
 received command truncate, not registered

**Comment by kportertx** [comment]
Are you using Aerospike 3.12?

**Comment by mhareesh** [comment]
we are using Aerospike Enterprise Edition build 3.9.1

**Comment by kportertx** [comment]
Truncate was added in 3.12.

**Comment by mhareesh** [comment]
Thanks

**Comment by arganzheng** [comment]
In order to complete remove sets in a namespace, we first truncate al the sets in a namespace, and the `show sets` command show that all sets now have 0 objects, and then we restart the Aerospike-Server in order to remove empty sets(really not  good user friendly..), we are surprice to find that all the deleted data now come back!

**Comment by mtendjou** [comment]
The truncate command does not durably delete records in the Community Edition. The Enterprise Edition provides durability through the truncate command.
