### ISSUE TITLE
aql output error when using json mode

### ISSUE THREAD

**Issue by sel-fish** [aerospike/aerospike-server#127]
**As there is no github project for aql, I just post the issue here. Please feel free to remind me if that behavior is improper.**

When I tried to look into [this question](http://stackoverflow.com/questions/36937415/aql-different-results-from-stream-udf-depending-on-output-style-table-json#),  I reappeared the problem, and I think that maybe a bug of aql.  Just give a brief description : 

When I run aql with the default output style (table), I got the result as expected.

```
192:auction fenqi$ aql -o table -f do_aggregate.aql
RUN 'do_aggregate.aql'
AGGREGATE get_trans_sum.trans_sum_by_years() ON test.auction
+-------------------------------------------------+
| trans_sum_b...                                  |
+-------------------------------------------------+
| MAP('{"trans":1, "auctions":1, "v":{1998:1}}')  |
+-------------------------------------------------+
1 row in set (0.083 secs)
```

But when I run aql with json output style, the field of 'v' become empty :

```
192:auction fenqi$ aql -o json -f do_aggregate.aql
RUN 'do_aggregate.aql'
AGGREGATE get_trans_sum.trans_sum_by_years() ON test.auction
[
  {
    "trans_sum_b...": {
      "trans": 1,
      "auctions": 1,
      "v": {}
    }
  }
]
```

The version of my aql is [3.8.2 Mac OS X](http://www.aerospike.com/download/tools/3.8.2/).
As I compare the return of aerospike-server when run these two commands, they are the same, so I guess there may be bug in aql.

```
  159   0x0050:  0001 0000 0027 0113 0007 5355 4343 4553  .....'....SUCCES
  160   0x0060:  5383 a603 7472 616e 7301 a903 6175 6374  S...trans...auct
  161   0x0070:  696f 6e73 01a2 0376 81cd 07ce 01         ions...v.....
  162 01:57:56.012615 IP localhost.hbci > localhost.57735: Flags [P.], seq 98:128, ack 144, win 42853, options [nop,nop,TS val 976647953 ecr 976647941], length 30
  163   0x0000:  4500 0052 6692 4000 4006 0000 7f00 0001  E..Rf.@.@.......
```

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
