### ISSUE TITLE
Aerospike: Getting UnsupportedFeature exception, CDT list feature is not supported

### ISSUE THREAD

**Issue by dhanasekaran1980** [aerospike/aerospike-server#128]
I am using Aerospike 3.7.3 and python client 2.0.1

Tested under single as-well-as 2 node cluster.

Appending items to CDT (List) where each item it 1KB. Appending items till the record size reaches 1M. Then incrementing the key.

Throwing below exception after writing few lakh of items.

exception.UnsupportedFeature: (16L, 'CDT list feature is not supported', 'src/main/client/operate.c', 1290)

Also very few times I am getting exception.DeviceOverload: (18L, 'AEROSPIKE_ERR_DEVICE_OVERLOAD', 'src/main/aerospike/as_command.c', 1082)

Every time I clear the keys and re-run, I am getting either of these two exceptions, exception.UnsupportedFeature being the majority.

**Comment by wchu-citrusleaf** [comment]
Re - DEVICE_OVERLOAD is because the persistent layer is not keeping up. See https://discuss.aerospike.com/t/write-fail-queue-too-deep/3009
 
Re - UnsupportedFeature. Maybe you can provide the server side log when this happens?

Thanks
