### ISSUE TITLE
aerospike client i/o blocks for all clients when there is a fault

### ISSUE THREAD

**Issue by kaniini** [aerospike/aerospike-server#129]
hello,

while developing an asyncio version of our own custom python aerospike client (http://github.com/kaniini/aerospike-py), we noted that there was a fault resulting in a deadlock of all client i/o for any connected clients, if a single client connects and then fails to perform any i/o.

this is probably a bug in the way i/o is handled by the code (perhaps not waiting for input before servicing the socket), but may also be intentional.  if it's intentional, we suggest documenting this on the wire protocol spec.

thanks!

**Comment by kaniini** [comment]
this has been confirmed to happen between aerospike fabric members themselves too!  this bug is really serious!

**Comment by wchu-citrusleaf** [comment]
The following are the expected behaviors - 
(1) client/server sockets persist the connection for a period of time (configured by proto-fd-idle-ms=60000)
http://www.aerospike.com/docs/reference/configuration#proto-fd-idle-ms

(2) node-to-node (aka fabric) connections are always kept alive through keep-alive messages.

Can you describe in more detail what you consider an issue?

**Comment by kaniini** [comment]
so in may we saw a situation where if a client had an i/o fault (incomplete write), the entire cluster died.

then this evening, we added an additional node to the cluster and this caused the entire cluster to die because the ethernet port was maxed out on one of the nodes, thus causing lag in message delivery.

on an unrelated note, i am curious however about keep-alive messages, there is no discussion of them in the protocol spec.

**Comment by wchu-citrusleaf** [comment]
can you describe what does "caused the entire cluster to die"? 
(1) Did the server nodes all crash? 
(2) Or the node has hit proto-fd-limit (max number of allowed connections from client). 
If (2), it would seem that the client is opening up too many connections.

**Comment by kaniini** [comment]
the entire cluster stopped doing i/o.  no fd limit was hit, literally it froze.

**Comment by wchu-citrusleaf** [comment]
This doesn't happen with the Aerospike Clients. Most likely it's the result of special interaction with the special client.  Depending on what your namespace configuration is (data-in memory? ssd-only?), we can provide some guidance for you on further troubleshooting.
