### ISSUE TITLE
undefined reference to `cf_queue_reduce_pop'

### ISSUE THREAD

**Issue by YangQingACMIS** [aerospike/aerospike-server#130]
`make`
../../target/Linux-x86_64/obj/fabric/migrate.o: In function `emigration_pop':
/home/scidb/aerospike-server/as/src/fabric/migrate.c:641: undefined reference to `cf_queue_reduce_pop'
/home/scidb/aerospike-server/as/src/fabric/migrate.c:641: undefined reference to `cf_queue_reduce_pop'
collect2: ld returned 1 exit status
make[2]: *** [../../target/Linux-x86_64/bin/asd] Error 1
make[2]: Leaving directory `/home/scidb/aerospike-server/as/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/scidb/aerospike-server/as'
make: *** [all] Error 2
There is no define of cf_queue_reduce_pop in /home/scidb/aerospike-server/as/src/fabric/migrate.c. I don't know how to solve.

**Comment by psi-mankoski** [comment]
Thanks for the issue report!
Problem (out-of-date "common" submodule) resolved ~~ Please do: "git submodule update" then "make clean" then "make".
Let us know if you encounter more issues.
