### ISSUE TITLE
issue with java api and aerospike

### ISSUE THREAD

**Issue by PiyushMishra** [aerospike/aerospike-server#131]
Using Aerospike community edition there is a issue as below.

 WARNING (as): (signal.c:181) SIGSEGV received, aborting Aerospike Community Edition build 3.8.2.3 os ubuntu14.04
 WARNING (as): (signal.c:185) stacktrace: found 7 frames
 WARNING (as): (signal.c:185) stacktrace: frame 0: /usr/bin/asd(as_sig_handle_segv+0x35) [0x48dacc]
 WARNING (as): (signal.c:185) stacktrace: frame 1: /lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f198b756d40]
 WARNING (as): (signal.c:185) stacktrace: frame 2: /usr/bin/asd(cf_queue_push+0xc) [0x556970]
 WARNING (as): (signal.c:185) stacktrace: frame 3: /usr/bin/asd(ssd_post_write+0x3bb) [0x513299]
 WARNING (as): (signal.c:185) stacktrace: frame 4: /usr/bin/asd(ssd_write_worker+0x118) [0x5134ff]
 WARNING (as): (signal.c:185) stacktrace: frame 5: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f198c932182]
 WARNING (as): (signal.c:185) stacktrace: frame 6: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f198b81a47d]

**Comment by wchu-citrusleaf** [comment]
Please check that your configuration file is correctly formed.
https://discuss.aerospike.com/t/segmentation-fault-sigsegv-when-enabling-data-in-memory/2615
