### ISSUE TITLE
[Enhancement request] Please provide native Rust driver

### ISSUE THREAD

**Issue by jacek99** [aerospike/aerospike-server#132]
http://rust-lang.org/

More and more we are looking at using it instead of C++ for low level  realtime systems, a native Rust driver would be very advantageous

Thank you

**Comment by bbulkow** [comment]
Jacek, I am interested in your use of Aerospike ( and potentially Rust ). Can you send me an email ( brian@aerospike.com ) and we can discuss ? Thanks.

**Comment by arthurprs** [comment]
The C interoperability is great so the implementation could just wrap over the C driver.

**Comment by rohitjoshi** [comment]
👍

**Comment by vertexclique** [comment]
@arthurprs nobody wants to wrap their high availability concerned db calls to an unsafe block. So better to have it in native.

**Comment by arthurprs** [comment]
@vertexclique I don't necessarily disagree with your opinion. At this point the C lib is very mature (it's used as basis for others too, Python, Ruby, etc..) and it can provide a very nice layer to build an initial Rust client. Doing it from scratch could take A LOT more effort.

**Comment by wchu-citrusleaf** [comment]
An initial v0.0.1 release is now available on [crates.io](https://crates.io/crates/aerospike). Documentation can be found at [docs.rs](https://docs.rs/aerospike/) and the source code is available in the [aerospike-client-rust repo](https://github.com/aerospike/aerospike-client-rust). Please note that this is a work in progress and that the public API of the client is still subject to change. Feedback, bug reports and pull requests are welcome!
