### ISSUE TITLE
INCR and APPEND ops may erroneously fail with AS_PROTO_RESULT_FAIL_NOTFOUND due to expiry

### ISSUE THREAD

**Issue by kaniini** [aerospike/aerospike-server#133]
Under sufficient load, it is possible to observe a race condition where mutation of a particle may fail due to `as_record_is_expired()` returning true.

In these cases, a workaround is to retry the transaction, in which case the mutation will start over with a fresh particle as expected.  In reality, however, a fresh particle should be initialised with a new TTL deadline when `as_record_is_expired()` is called.  In some parts of the code, but not others, this already occurs.  Examples of this discrepancy can be observed in [thr_batch.c](https://github.com/aerospike/aerospike-server/blob/8c05eb9d99637f3060f366f853364d4e7dfce86d/as/src/base/thr_batch.c#L112-L115) and [thr_rw.c](https://github.com/aerospike/aerospike-server/blob/1538bd512f9ec264232c596bcf769011ad20853d/as/src/base/thr_rw.c#L4605-L4608).  Although for the thr_rw.c case above, this is intentional and dependent on `must_not_create == true` so is correct here.  There is however, weirdness in `read_local()` that I find suspect.

In all cases, mutation ops should start from a freshly initialised particle if expired, so INCR on an expired record should create a new record with the bin initialised to `1`.

**Comment by wchu-citrusleaf** [comment]
The expected behavior is that all writes ("mutations") will indeed start over with a fresh particle, unless the client policy leads to `must_not_create`. This does not apply to reads. All reads will simply return NOT_FOUND if the record expired.

Can you provide sample code where you observe writes on an expired record does not succeed?

Thanks.
