### ISSUE TITLE
Incorrect use of usleep() may negatively impact performance due to bad scheduler decisions

### ISSUE THREAD

**Issue by kaniini** [aerospike/aerospike-server#134]
In many areas of the code, you can find [patterns like this](https://github.com/aerospike/aerospike-server/blob/8c05eb9d99637f3060f366f853364d4e7dfce86d/as/src/base/thr_batch.c#L168-L171):

``` c
int yield_count = 0;

while (1) {
    if (yield_count % something)
        usleep(1);
}
```

These should be replaced by `sched_yield()` so that the scheduler may make the correct decision about which threads should run.

It may also be interesting to look at Intel's TBB library and implement a proper workqueue instead.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.

**Comment by bbulkow** [comment]
Despite the name "yeild_count" the goal is to not to yield, nor is it to wait for a workqueue element. If the goal was to yield, it would be calling sched_yield.
