### ISSUE TITLE
[ENHANCEMENT] Support for Unix domain sockets

### ISSUE THREAD

**Issue by devilboy505** [aerospike/aerospike-server#135]
Unix domain sockets are typically at least 50% faster than TCP loopback. While this feature wouldn't help with non-unix systems and and when the server and client exist on different hosts, it would help increase localhost throughput tremendously.

**Comment by bbulkow** [comment]
Agreed. Aerospike is not architected for cases where the client and server are on the same machine. It's a client-server system, with a distributed set of servers and random distribution, so we have chosen not to optimize for same server performance.

If you have a case where you intend to use Aerospike in a single-server only mode, and intend to have the client and server always on the same machine, and you find Unix domain sockets provide a huge performance advantage, please feel free to submit a pull request to the server and the clients involved --- we'll consider it.
