### ISSUE TITLE
"cli" script name is too vague, and likely to conflict with other packages

### ISSUE THREAD

**Issue by roncemer** [aerospike/aerospike-server#137]
Please rename /usr/bin/cli to something else.  The name "cli" is too vague, and potentially duplicated by other packages which made the same mistake when naming their binaries.

Is there even a good reason to have both cli and ascli in /usr/bin?  It seems that ascli can do everything that's needed, so it should be in /usr/bin, so the easiest solution could be to just not put cli in /usr/bin, or not have cli at all.

**Comment by wchu-citrusleaf** [comment]
We are looking at retiring both ascli and cli in the near future. Thanks.

**Comment by wchu-citrusleaf** [comment]
cli is now deprecated in 3.9 and should no longer conflict
