### ISSUE TITLE
get a random key from aerospike

### ISSUE THREAD

**Issue by greallycoolg** [aerospike/aerospike-server#138]
how did i get random key from aerospike like redis run randomkey can return a random key?

**Comment by bbulkow** [comment]
Not currently. You can "subsample" on a query and return a random sub-sampling of the response.

So we can prioritize the request, what do you use this feature for ?

**Comment by greallycoolg** [comment]
thanks for answer！sometimes i just want to know what the key like and the value like in database, just  by run a simple command cat get it .

**Comment by wchu-citrusleaf** [comment]
Building on @bbulkow's answer - yes, you can definitely do so today by doing a sub-sampling scan, which will return the key (if stored) and all other meta data.
