### ISSUE TITLE
run pmap get error message

### ISSUE THREAD

**Issue by greallycoolg** [aerospike/aerospike-server#139]
this is asmonitor:

Traceback (most recent call last):
  File "/usr/bin/asmonitor", line 4029, in <module>
    main()
  File "/usr/bin/asmonitor", line 4013, in main
    RunCommand().onecmd(args.OneCommand)
  File "/usr/lib64/python2.6/cmd.py", line 219, in onecmd
    return func(arg)
  File "/usr/bin/asmonitor", line 2997, in do_pmap
    pid = int(parts[1])
ValueError: invalid literal for int() with base 10: 'partition'

this is asadm:

Admin> cluster pmap
ERR: invalid literal for int() with base 10: 'partition'

**Comment by greallycoolg** [comment]
i edit /usr/bin/asmonitor and print p , this is p:
namespace:partition:state:n_dupl:replica:origin:target:emigrates:immigrates:records:sub_records:ldt_version:version
next ,i modify 'for p in pinfo' to 'for p in pinfo[1:]'  and i get
test:1:S:0:0:0:0:0:0:0:0:0:16459962975549874801-1-0
test:2:S:0:1:0:0:0:0:0:0:0:16459962975549874801-1-0
test:3:S:0:1:0:0:0:0:0:0:0:16459962975549874801-1-0
test:4:S:0:0:0:0:0:0:0:0:0:16459962975549874801-1-0
test:5:S:0:1:0:0:0:0:0:0:0:16459962975549874801-1-0
test:6:A:0:2:0:0:0:0:0:0:0:0-0-0
test:7:A:0:2:0:0:0:0:0:0:0:0-0-0
......
these seem to be right output , but " asadm -e 'cluster pmap'  " command output same to the old
what should i do with asadm? should the asmonitor output be right?

**Comment by wchu-citrusleaf** [comment]
Seems that you may have an issue to report for asadm? Can you open a new issue on https://github.com/aerospike/aerospike-admin/
