### ISSUE TITLE
Aerospike cluster down and corrupted if a node is restarted during a cluster change

### ISSUE THREAD

**Issue by loicdescotte** [aerospike/aerospike-server#142]
Test done with 2 nodes and 4 nodes, replication factor = 2

Here are the steps to reproduce the issue with 2 nodes :
- stop node 1
- insert some data (enough to have a CLUSTER_CHANGE state during several minutes)
- start node 1  
--> `Error: (7) AEROSPIKE_ERR_CLUSTER_CHANGE`   (not too severe as we can still query - potentially inaccurate- data with the java client and failOnClusterChange = false)

- restart node 2
- query any node  
--> `AEROSPIKE_ERR_CLIENT Socket write error: 111`   

So it seems that when a node is sending his data to another node for replication, if this node is stopped or restarted, all the cluster dies.

The biggest problem about this is that it seems the only way to repair it is to delete all the data partition.

**Comment by wchu-citrusleaf** [comment]
Can you specify what you see on the server log?

**Comment by loicdescotte** [comment]
I have this kind of messages during CLUSTER_CHANGE : 

```
Jul 22 2016 15:40:48 GMT: INFO (drv_ssd): (drv_ssd.c:2072) device /dev/sda: used 39260544, contig-free 763058M (3052234 wblocks), swb-free 0, w-q 0 w-tot 149 (4.8/s), defrag-q 0 defrag-tot 0 (0.0/s) defrag-w-tot 0 (0.0/s)
Jul 22 2016 15:40:48 GMT: INFO (drv_ssd): (drv_ssd.c:2072) device /dev/sdb: used 39163008, contig-free 763058M (3052234 wblocks), swb-free 0, w-q 0 w-tot 149 (4.8/s), defrag-q 0 defrag-tot 0 (0.0/s) defrag-w-tot 0 (0.0/s)
````
During the second error (AEROSPIKE_ERR_CLIENT Socket write error: 111)  : 

```
Jul 22 2016 15:42:05 GMT: INFO (drv_ssd): (drv_ssd.c:3974) {calypso} loaded 4394899 records, 0 subrecords, /dev/sda 0%, /dev/sdb 0%
Jul 22 2016 15:42:07 GMT: INFO (drv_ssd): (drv_ssd.c:3974) {calypso} loaded 5730392 records, 0 subrecords, /dev/sda 0%, /dev/sdb 0%
```

**Comment by loicdescotte** [comment]
For each aql request, I have the same error in the logs : 

```
WARNING (scan): (scan.c:612) basic scan job not started - migration
```

**Comment by loicdescotte** [comment]
It seems that if we are very patient (about 30 minutes) the node are back into AEROSPIKE_ERR_CLUSTER_CHANGE

**Comment by wchu-citrusleaf** [comment]
It looks like you have secondary index in your system. The log shows that the node is still in the starting up process, rebuilding secondary index. After 30 minutes, the sindex is rebuilt, and node is available again.

The restarted node should be the only one that's not available. Do basic read/write succeed during this time?

**Comment by loicdescotte** [comment]
We have 2 indexes for 2 different sets.  
Is it a problem to have a secondary index? 

Basic read work during CLUSTER_CHANGE state but not during the second error (AEROSPIKE_ERR_CLIENT Socket write error)

**Comment by wchu-citrusleaf** [comment]
When nodeX departs from the cluster, the client needs a few seconds before it re-adjust itself to stop sending request to nodeX. During this few seconds, it is expected to see socket error, for all operations (read,write, query etc). After that, all transactions should no longer have socket errors.

**Comment by loicdescotte** [comment]
So when a node is unavailable during x second, is the aerospike smart client able to switch to another node automatically, with a retry?

**Comment by wchu-citrusleaf** [comment]
The transactions would only be retried if the retry policy is set, and still within the transaction timeout that's set.
