### ISSUE TITLE
Renaming aerospike command line client.

### ISSUE THREAD

**Issue by SkyRocknRoll** [aerospike/aerospike-server#15]
I installed aerospike. My mono *cli* command was over written by "cli" command of aerospike. It would be better if we rename it to some other name.

**Comment by catalogoanatom** [comment]
Where I can find ascli or cli command line client?

**Comment by psi-mankoski** [comment]
"ascli" and "cli" are part of the Aerospike Tools package. While the Aerospike Tools are not yet open-sourced, tools builds are released as part of the Aerospike Server Community Edition, and "cli" is a Python source file that can be extracted from the tools package an Aerospike Server CE release "tgz" file.

**Comment by catalogoanatom** [comment]
Thanks
