### ISSUE TITLE
Feature Request: ArchLinux package support

### ISSUE THREAD

**Issue by kokizzu** [aerospike/aerospike-server#158]
Anyone can help with aerospike's archlinux package?

https://aur.archlinux.org/packages/aerospike-server-ce/

**Comment by kokizzu** [comment]
Why? Because ArchLinux is popular:

1	Mint	2866 --> deb
2	Debian	1663 --> deb
3	Ubuntu	1334 --> deb
4	openSUSE	1275 --> rpm
5	elementary	1084 --> deb
6	Manjaro	1031 --> tar.xz/pacman (archlinux)
7	Fedora	1011 --> rpm
8	Zorin	967 --> deb
9	CentOS	762 --> rpm
10	deepin	748 --> deb
11	Arch	717 --> tar.xz/pacman (archlinux)
12	Antergos	609 --> tar.xz/pacman (archlinux)

other than DEB and RPM, TAR.XZ is most popular one package.

![image](https://cloud.githubusercontent.com/assets/1061610/20624962/9b898504-b342-11e6-9e8d-b5560760ea51.png)

**Comment by akayami** [comment]
I would like to add my support to this request. Support of arch would be greatly welcome. At this moment neither server nor clients can be deployed on arch. All competitive projects support it out of the box (or through maintained AUR). 

Aerospike looks very interesting, and I'm considering it for some projects, but the current platform support is too limited.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.

**Comment by bbulkow** [comment]
Aerospike is an open-source project, and its makefiles are published. Anyone who is interested in supporting Arch Linux is free to submit a pull request. Aerospike would be happy to accept that pull request.
