### ISSUE TITLE
Aerospike Server memory error (8) on client

### ISSUE THREAD

**Issue by kokizzu** [aerospike/aerospike-server#162]
There is warning:
`Nov 28 2016 08:15:04 GMT: WARNING (rw): (write.c:789) {namespace-2}: write_master: drives full`

Isn't it auto split to another file when the `file` is full (just like normal database)? 
or I should define each `file` manually one by one?

my config:

```
namespace namespace-1 {
  replication-factor 2
  memory-size 4G
  default-ttl 0 # 30 days, use 0 to never expire/evict.
  storage-engine device {
    file /home/asd/aerospike-server/namespace-1
    filesize 128M
  }
}

```

So my assumption is wrong, that it's automatically create a new file:
`/home/asd/aerospike-server/namespace-1.1`,
`/home/asd/aerospike-server/namespace-1.2`,
`/home/asd/aerospike-server/namespace-1.3` and so on?

**Comment by wchu-citrusleaf** [comment]
Aerospike does not automatically create new files. The space you give here, 128M, is how much is specified for the system, which is obviously too little.

See http://www.aerospike.com/docs/operations/configure/namespace
