### ISSUE TITLE
Failures during scans with long pauses between items

### ISSUE THREAD

**Issue by allenluce** [aerospike/aerospike-server#165]
I encounter a bunch of errors when doing a scan using the Go client with 3.10.1.1. My particular scan does a lot of work between each item (2000+ gets for each scan item).  The problem seems to be related to a change to blocking reads w/timeouts in a227c908. If I change the value of `CF_SOCKET_TIMEOUT` to -1, I get no errors.

I logged this first as [a client issue](https://github.com/aerospike/aerospike-client-go/issues/167).

**Comment by wchu-citrusleaf** [comment]
The server change is required to accommodate certain VM environments where client exiting the scan does not properly close the socket, thus hanging the scan indefinitely. 

In general, it's best for the client to keep the in-line processing to be minimal/post scan, to get the best snapshot of the scan, particularly if there are multiple concurrent scans required. Would that be applicable?

**Comment by allenluce** [comment]
It would be nice to have that as a tunable parameter at least. It's a bit of a bummer that the "fix" for this is to cache the entirety of a scan run in memory.

**Comment by wchu-citrusleaf** [comment]
Thanks will consider this.

**Comment by kportertx** [comment]
I believe this was fixed with [3.12.1](https://www.aerospike.com/download/server/notes.html#3.12.1) "Write idle-time-out now configurable from client.".

Let us know if this is still a concern.
