### ISSUE TITLE
Can i save igbinary data in aerospike

### ISSUE THREAD

**Issue by evalsocket** [aerospike/aerospike-server#166]
Actually I am trying to save data in igbinary  formate in aerospike but when i am checking data in aerospike then i found keys but respective data is empty string.

>  $key = $aerospikeObj->createKey(AERO_DB_NAMESPACE,$aeroConfig,strtoupper($process_key));
> $bins = ["data" => igbinary_serialize($document)];
> $aerospikeObj->setKey($key,$bins,AERO_URC_EXPIRY_TIME);

**Comment by wchu-citrusleaf** [comment]
Yes, Aerospike does support saving binary data. Recommendation is to look into the specific client examples for inserting binary data bin. If there is any issues, let's discuss on the client repository. Thanks.

**Comment by evalsocket** [comment]
When i am converting data into igbinary and try to save it into aerospike it insert as a empty string "". I am using PHP client
