### ISSUE TITLE
Incorrect node-id generated in rack-aware dynamic mode, and node-id-interface is ignored.

### ISSUE THREAD

**Issue by dmytroleonenko** [aerospike/aerospike-server#169]
More info here: https://discuss.aerospike.com/t/configuration-documentation-is-a-mess/3756
Just not to repeat myself
node-id-interface is silently ignored in the dynamic clustering mode and is generated based on the first address of the first interface which is the "lo" loopback in most cases effectively leading to the cluster being unable to form because of duplicating node ids

**Comment by kportertx** [comment]
https://github.com/citrusleaf/aerospike-server/blob/master/as/src/base/cfg.c#L730

The *node-id-interface* seems to have been misplaced into the service context instead of network.service.

As a workaround you should be able to set the config in the service context.

**Comment by dmytroleonenko** [comment]
Well... as I said it just doesn't complain about the syntax. But the node-id-interface eth0 doesn't do anything. As you can see https://github.com/aerospike/aerospike-server/blob/master/as/src/base/cfg.c#L4216 it doesn't honor _node-id-interface_ and just uses the first address of the first up-and-running interface

**Comment by wchu-citrusleaf** [comment]
This is now fixed in 3.11.0.2
