### ISSUE TITLE
Feature request: Mode to allow reads to always reserve local node.

### ISSUE THREAD

**Issue by vytas-dauksa** [aerospike/aerospike-server#171]
In our use case we fetch all database every second. when a node goes down there are few seconds when part of the data is not available and fail_on_cluster_change is false. when a node comes back due to migration data availability is affected for minutes.

We replicate to every node ( similar scenario described here https://discuss.aerospike.com/t/read-policy-replica-closest-and-or-local/1517 ), so data is actually available. This was confirmed by running some failure scenarios with following hacks:
AS C client:
```
--- a/src/main/aerospike/aerospike_scan.c
+++ b/src/main/aerospike/aerospike_scan.c
@@ -777,7 +777,7 @@ aerospike_scan_async(
        as_error_reset(err);

        as_nodes* nodes = as_nodes_reserve(as->cluster);
-       uint32_t n_nodes = nodes->size;
+       uint32_t n_nodes = 1; //nodes->size;

        if (n_nodes == 0) {
                as_nodes_release(nodes);
```

AS Server:
```
+++ b/as/src/fabric/partition.c
@@ -658,6 +658,8 @@ find_best_node(const as_partition* p, const as_namespace* ns, bool is_read)
        bool acting_master = p->target != 0;

        cf_node best_node = (cf_node)0;
+       // XXXXX
+       return g_config.self_node;

        if ((is_final_master && is_sync) || acting_master) {
                best_node = g_config.self_node;
```

Would you consider introducing behaviour to prefer fetching from localhost or specified node when it has the data, but is not acting as a master for it?

**Comment by wchu-citrusleaf** [comment]
Interesting thought indeed and makes sense. Will have in backlog, but probably not anytime soon.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
