### ISSUE TITLE
Create record with ttl from udf

### ISSUE THREAD

**Issue by stgleb** [aerospike/aerospike-server#172]
I have a snippet of code on lua, it checks a bunch of limits and return result. It works in redis with expire command. Is it possible to do the same thing(create record with ttl) from aerospike udf?

`redis.call('expire', key, remain)`

**Comment by wchu-citrusleaf** [comment]
Yes, it is possible to create/update records with specific TTL's. There are a few entry-points for the TTL value to use. Please see 

http://www.aerospike.com/docs/udf/developing_record_udfs.html#record-ttl-and-udf
