### ISSUE TITLE
dropping incoming client connection

### ISSUE THREAD

**Issue by submarineblue** [aerospike/aerospike-server#175]
l recently encountered situation that cannot make new connections to asd.
The log shows "WARNING (demarshal): (thr_demarshal.c:564) dropping incoming client connection: hit limit 15001 connections".
l use C client and have four nodes with two copies. asd version is Aerospike Community Edition build 3.9.0.

**Comment by submarineblue** [comment]
Anyone has any thoughts about this? Or anyone has encountered the same situation?

**Comment by wchu-citrusleaf** [comment]
This is typically symptomatic of client application misuse of the library. As a starter, one can limit the appropriate max_conns_per_node via configuration, which may lead to more details on why such usage pattern result. Also, checking in discuss.aerospike.com for further community hints.

**Comment by submarineblue** [comment]
l use citrusleaf_client_libevent2_2.1.44 and follow the examples, and the runtime options are all default: "socket_pool_max" is 300. Besides,l run netstat and get the number of client connections to server port 3000 is only around 300.

And l found many socks reported by lsof as "can't identify protocol" in asd and after tracking l found that they are related to port 3001. So l suspect if this problem is caused by cluster fabric or something.
