### ISSUE TITLE
I want to get the enterprise edition of aerospike, can you give me some help?

### ISSUE THREAD

**Issue by baozh** [aerospike/aerospike-server#176]
I'm a software engineer working at eleme (https://www.ele.me/) in China, Recently doing something about multi-datacenter disaster recovery. I learned aerospike provides xdr(cross datacenter replication) function from a paypal architect's speech, so would like to do some benchmarks to get the performance of aerospike(Enterprise Edition). 
We submitted our information (refer to http://www.aerospike.com/enterprise-trial/), but haven't received any call. then, We email to sales.cn@aerospike.com (refer to http://www.aerospike.com/chinese/), still haven't got any reply.

Any one can give me some help?

**Comment by wchu-citrusleaf** [comment]
Have forwarded info to sales.
