### ISSUE TITLE
GeoSpatial query performance

### ISSUE THREAD

**Issue by seungryulchoisc** [aerospike/aerospike-server#177]
Hi,

We were conducting loadtest on Aerospike for geospatial queries, but we only got around 150 TPS on 32 core single node cluster.  We loaded OpenStreetMap admin-level-8 map, which has about 174K polygons. The queries are lat,lng of popular locations and we used benchmark.go in aerospike-client-go library for the loadtest.

When running loadtest, CPU utilization was only 130% on 32 core machine, meaning only 1 core was fully utilized.  Looking further, we found a sign of lock contention at as_record_get_live() within query_io() (in thr_query.c, that goes down to olock_vlock() in as_index_sprig_get_vlock() in index.c).

Changing query-threads, partition-tree-locks, and partition-tree-sprigs did not help.  And varying client concurrency did not help either.

Is there a way to fully utilize the available CPU cores to get higher TPU?

**Comment by wchu-citrusleaf** [comment]
This sounds more like a data model issue where the same record (or a handful of records) are always  queried. Are there ways to enhance the data-model so you do not querying for hot-keys?

**Comment by wchu-citrusleaf** [comment]
closing due to reposting https://discuss.aerospike.com/t/geospatial-query-performance-suboptimal-and-varies/3921
