### ISSUE TITLE
Multi-Filter (AND, OR, NOT) not support?

### ISSUE THREAD

**Issue by arganzheng** [aerospike/aerospike-server#179]
Aerospike not support multiple filters? like select * from test.test where name = "argan" and age BETWEEN 10 and 10?

**Comment by wchu-citrusleaf** [comment]
In version 3.12.0 just recently released, this is now supported. 
See http://www.aerospike.com/docs/guide/predicate.html

**Comment by arganzheng** [comment]
> Predicate filtering is introduced in Aerospike Server 3.12. Predicate expressions provide a mechanism for additional filtering on the resultset of a secondary index query or scan operation.

Predicate filtering is not multiple  secondary index query? Rather multiple filter on the secondary index query result?

**Comment by wchu-citrusleaf** [comment]
Your understanding is correct. Aerospike does not support compound indexes.
