### ISSUE TITLE
primary index & Stop Writes

### ISSUE THREAD

**Issue by playchao** [aerospike/aerospike-server#183]
a cluster  4 nodes（64G RAM  1.7T*3 SSD）
when use ssd store，just insert 17 billion records，the memory is full and Stop Writes is true

4 nodes store the same primary index？

**Comment by mtendjou** [comment]
17 billion records would occupy: (17*10^9*64)/(1024*1024*1024) =~1TiB of RAM (and ~2TiB if replication factor 2).

Your 4 nodes would only have 256GiB of RAM (not accounting for RAM for the OS and the high water marks guiding the stop writes... default of 90%).
