### ISSUE TITLE
Aql query for a set with dot character in its name  

### ISSUE THREAD

**Issue by mluscon** [aerospike/aerospike-server#185]
Hi, 
is there any way how to query sets named like e.g. "myset-1.1"?

**Comment by wchu-citrusleaf** [comment]
This is a known limitation of aql. However, not a limitation if you directly use any client libraries.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
