### ISSUE TITLE
Segfault on aerospike_connect

### ISSUE THREAD

**Issue by diffuse** [aerospike/aerospike-server#186]
Aerospike client segfaults immediately on aerospike_connect

Connecting using the C libev client.

 
`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff26e651a in __GI_abort () at abort.c:89
#2  0x00007ffff2728200 in __libc_message (do_abort=do_abort@entry=2, 
    fmt=fmt@entry=0x7ffff283ccd8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff273188a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, 
    str=0x7ffff283ce30 "free(): invalid next size (normal)", action=3) at malloc.c:5046
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:3902
#5  0x00007ffff27352bc in __GI___libc_free (mem=<optimized out>) at malloc.c:2982
#6  0x00007ffff2776f4d in __closedir (dirp=dirp@entry=0x607a80) at ../sysdeps/posix/closedir.c:50
#7  0x00007ffff74e8e39 in update (m=<optimized out>, e=<optimized out>) at src/main/mod_lua.c:393
#8  0x00007ffff74d620d in as_module_configure (m=<optimized out>, config=config@entry=0x7fffffffdd50)
    at src/main/aerospike/as_module.c:47
#9  0x00007ffff74a31ef in aerospike_init_lua (config=config@entry=0x607390)
    at src/main/aerospike/aerospike.c:99
#10 0x00007ffff74a336e in aerospike_connect (as=0x6071d0, err=0x7fffffffe010)
    at src/main/aerospike/aerospike.c:160
`

Packages installed:
- aerospike-server-community-3.12.1.1-1.el7.x86_64
- aerospike-client-c-libev-4.1.6-1.el7.x86_64
- aerospike-client-c-libev-devel-4.1.6-1.el7.x86_64
- aerospike-client-python-0.1-1486326073.fc25.x86_64
- aerospike-tools-3.12.1-1.el7.x86_64

**Comment by BrianNichols** [comment]
Make sure you have recompiled your code with the C client 4.1.6 header files.  If that still fails, please provide a reproducible test case.
