### ISSUE TITLE
[ARM support] Unable to compile for arm64.

### ISSUE THREAD

**Issue by hyb19960105** [aerospike/aerospike-server#19]
I find a compilation issue, as follows:
The platform I use is arm64, but error when compiling module luajit:
version:47e253a363983209b814e16bea986df222ce9e77
------------------------------------------------------------------------------
mkdir -p ./target/Linux-aarch64/gen ./target/Linux-aarch64/lib ./target/Linux-aarch64/bin
mkdir -p ./target/Linux-aarch64/obj/base ./target/Linux-aarch64/obj/fabric ./target/Linux-aarch64/obj/storage ./target/Linux-aarch64/obj/geospatial ./target/Linux-aarch64/obj/transaction ./target/Linux-aarch64/obj/xdr
build/gen_version community ubuntu16.04 > ./target/Linux-aarch64/gen/version.c
cc -o target/Linux-aarch64/obj/version.o -c target/Linux-aarch64/gen/version.c
make -C /home/aerospike/aerospike-server/modules/luajit Q= TARGET_SONAME=libluajit.so CCDEBUG=-g
make[1]: Entering directory '/home/aerospike/aerospike-server/modules/luajit'
==== Building LuaJIT 2.0.3 ====
make -C src
make[2]: Entering directory '/home/aerospike/aerospike-server/modules/luajit/src'
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
Makefile:231: *** Unsupported target architecture.  Stop.
make[2]: Leaving directory '/home/aerospike/aerospike-server/modules/luajit/src'
Makefile:103: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/home/aerospike/aerospike-server/modules/luajit'
Makefile:54: recipe for target 'aslibs' failed
make: *** [aslibs] Error 2
--------------------------------------------------------------
I found that it can compile normally with v2.1 of luajit(but it is no stable version), can I replace the original

**Comment by kportertx** [comment]
Aerospike currently doesn't support ARM.

**Comment by mariaefi29** [comment]
Dear developers,

Do you have any updates on that issue? With M1 release it is very important, I suppose.

Unfortunately, I cannot start my application locally for developing now on my new laptop with M1 chip that was given to me at work :(

**Comment by kportertx** [comment]
ARM support is a high-priority item on our roadmap.

**Comment by robd003** [comment]
Any updates on ARM support? I'd like to use Aerospike on AWS Graviton2 instances.

**Comment by ramunasd** [comment]
Seems that aerospike team even does not try to compile on non adm64. Take look at common dependency(for server and clients), it has wrong exclusion list. They would notice that on first attempt to compile.
https://github.com/aerospike/aerospike-common/commit/3ec9b2a6de446801745e2ff23ceb75a8a78a1537

**Comment by kportertx** [comment]
@ramunasd, our investigational ARM port doesn't use common's `master` branch - see `tsan2`.

@robd003, Internally we've built and tested an ARM port as part of an initial investigational effort to estimate the overall cost of such a port. This investigation has highlighted a few porting strategies, each with its own advantages and disadvantages, which are being debated. A GA ARM release is planned for later this year.

**Comment by robd003** [comment]
@kportertx It'd be great if you guys pushed the port to a branch here so the community could help fix issues

**Comment by robd003** [comment]
@kportertx It'd be great if you guys could push the port here so the community could help fix issues. I wasn't able to find the `tsan2` branch anywhere

**Comment by robd003** [comment]
@kportertx any update on this?

I'd really like to use aerospike on AWS Graviton2 instances since we've fully migrated our fleet away from Intel.

**Comment by kportertx** [comment]
This is the primary feature for the upcoming 6.2. Our tests will likely focus on graviton 2.

**Comment by kportertx** [comment]
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0
