### ISSUE TITLE
truncated data in a namespace comes back after server restart

### ISSUE THREAD

**Issue by arganzheng** [aerospike/aerospike-server#191]
In order to complete remove sets in a namespace, we first truncate all the sets in a namespace, and the show sets command show that all sets now have 0 objects, and then we restart the Aerospike-Server in order to remove empty sets (really not good user friendly..), we are surprised to find that all the deleted data now come back!

**Comment by kportertx** [comment]
Truncate is durable on Aerospike Enterprise.

http://www.aerospike.com/products/
