### ISSUE TITLE
 undefined reference to `je_chunksize_mask' and `je_huge_aalloc'

### ISSUE THREAD

**Issue by cih-y2k** [aerospike/aerospike-server#192]
Hi all, I'm trying to port aerospike-server to OSv (https://github.com/cloudius-systems/osv) by compiling aerospike server to asd.so. But when link libcf.so to asd.so, linker failed looking up `je_huge_aalloc' and `je_chunksize_mask' from libjemalloc.so.2 while other symbols such as `jem_mallctl', `jem_sallocx', .. is present.
Another point, when I compile asd with libjemalloc.a, there is no such errors, can anyone give me a hint?
Thank you in advance!

**Comment by tlopatic** [comment]
Hey there,

Thanks for reaching out. Your project sounds very cool!

The dynamic JEM library hides internal symbols, so that it's not possible to link against them. (Check out the `-fvisibility` GCC option, if you're interested in how they do this.) The symbol visibility rules don't apply to static linking, and that's why static linking works for you.

For tighter integration, Aerospike needs access to the two internal symbols that you mention. You can force these symbols to be exported also by the dynamic JEM library by adding the JEMALLOC_EXPORT macro to the definitions of these two symbols in the corresponding .c files.

Like this, for example:

```
diff --git a/src/chunk.c b/src/chunk.c
index dff537f..703b1e3 100644
--- a/src/chunk.c
+++ b/src/chunk.c
@@ -15,6 +15,7 @@ rtree_t		chunks_rtree;
 
 /* Various chunk-related settings. */
 size_t		chunksize;
+JEMALLOC_EXPORT
 size_t		chunksize_mask; /* (chunksize - 1). */
 size_t		chunk_npages;
 
diff --git a/src/huge.c b/src/huge.c
index 3a2877c..c3502ed 100644
--- a/src/huge.c
+++ b/src/huge.c
@@ -411,7 +411,7 @@ huge_dalloc(tsdn_t *tsdn, void *ptr)
 	arena_decay_tick(tsdn, arena);
 }
 
-arena_t *
+JEMALLOC_EXPORT arena_t *
 huge_aalloc(const void *ptr)
 {
 ```
The JEMALLOC_EXPORT macro overrides the visibility of the symbols that it is applied to. With the above change, you should be able to link dynamically with JEM.

**Comment by cih-y2k** [comment]
Thank you @tlopatic I'll give it a try.

**Comment by cih-y2k** [comment]
Hi @tlopatic , with your help, I've built aerospike server to asd.so successfully. But I have another problem. OSv does not support sbrk() system call at the moment that jemalloc depends on, so I want to build aerospike without jemalloc. Following aerospike's README, I tried to build with make USE_JEM=0, but there was no difference, because libcf.so still depends on jemalloc. Then I looked at cf's source file, as you know, there are some extern references there without any macro guarding something like that.

Do you know how to build aerospike without jemalloc? Thank you!

**Comment by bbulkow** [comment]
Sounds like bit rot. At Aerospike, we've found JE_MALLOC to be such a great library that we don't do much building without it, and I might hazard the idea that if OSv is serious about supporting servers, they should make friends with the JeMalloc library -- it's a library used by a lot of serious server developers.

But that's philosophy... you don't want to hear it, I imagine, you want a building server! Cool.

I would hazard a guess you'll need to cover the externs with a macro, which might require understanding enough of the . This is an open source project, so if you submit your pull requests, they can be incorporated in the main line, assuming you can sign the contributory license agreement. If you need help understanding the code in that area, this issue or maybe another about "doesn't build with USE_JEM=0" would be a great place to have the discussion.

**Comment by tlopatic** [comment]
Brian is correct; this is a documentation bug. The documentation wasn't updated when the code switched to be JEM-only. There's now a pretty tight integration of Aerospike with JEM, which allows for things like improved allocation profiling, etc.

That said, you have two options, I think.

1. If it's only `sbrk()`, then one quick hack would be to manually run the `configure` script in the `modules/jemalloc` subdirectory of the Aerospike source code tree as follows:

    `./configure sbrk_deprecated=1 "EXTRA_CFLAGS=-I/opt/valgrind/include -I/usr/local/include" --with-jemalloc-prefix=jem_`

    This runs `configure` in pretty much the same way as the Aerospike Makefile would run it, with the difference that it also passes `sbrk_deprecated=1`, which makes JEM not use `sbrk()`, just `mmap()`.

2. The second option is a little more involved. It rips a lot of stuff out of `cf/src/alloc.c`.

    This is how `cf/src/alloc.c` works: It provides the complete standard allocation API, i.e., `malloc()`, `free()`, etc. These functions in `alloc.c` implement accounting and delegate the real allocation work to JEM. JEM is compiled to use the `jem_` prefix for the allocation API. So, for example, `malloc()` in `alloc.c` would do the accounting work, and then invoke JEM's `jem_malloc()` to do the actual allocation.

    What you can do is rip out the complete standard allocation API from `alloc.c`, so that you can link with your own allocator. Aerospike will then invoke your `malloc()`, your `free()`, etc. instead of the `malloc()`, `free()` etc. functions provided by `alloc.c` as it does now.

    There are actually a few more functions in `alloc.c`, implementing statistics and other optimizations, but for the moment, you could just stub them out, i.e., replace them with dummy functions, and worry about these optimizations later, by adding this functionality back in.

    Lastly, `alloc.c` is also home to the reference-counted allocation API, the `cf_rc_*()` functions, which need to be slightly adapted.

Long story short, replacing `alloc.c` with the following code should make Aerospike work with any memory allocator you link it with. As I said before, though, this will get rid of a few optimizations and statistics. But you can always worry about this later. Let's first get your port to OSv to link properly.

Sorry for the long code quote. I don't know how to attach files to GitHub issues.

```
/*
 * alloc.c
 *
 * Copyright (C) 2008-2017 Aerospike, Inc.
 *
 * Portions may be licensed to Aerospike, Inc. under one or more contributor
 * license agreements.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 */

#include "enhanced_alloc.h"

#include <stdlib.h>

#include "citrusleaf/cf_atomic.h"

__thread int32_t g_ns_arena = -1;

void cf_alloc_init(void)
{
}

void cf_alloc_set_debug(cf_alloc_debug debug)
{
	(void)debug;
}

int32_t cf_alloc_create_arena(void)
{
	return 0;
}

void cf_alloc_heap_stats(size_t *allocated_kbytes, size_t *active_kbytes, size_t *mapped_kbytes,
		double *efficiency_pct, uint32_t *site_count)
{
	(void)allocated_kbytes;
	(void)active_kbytes;
	(void)mapped_kbytes;
	(void)efficiency_pct;
	(void)site_count;
}

void cf_alloc_log_stats(const char *file, const char *opts)
{
	(void)file;
	(void)opts;
}

void cf_alloc_log_site_infos(const char *file)
{
	(void)file;
}

void *cf_alloc_malloc_arena(size_t sz, int32_t arena)
{
	(void)arena;
	return malloc(sz);
}

void *cf_alloc_calloc_arena(size_t n, size_t sz, int32_t arena)
{
	(void)arena;
	return calloc(n, sz);
}

void *cf_alloc_realloc_arena(void *p, size_t sz, int32_t arena)
{
	(void)arena;
	return realloc(p, sz);
}

void *
cf_rc_alloc(size_t sz)
{
	size_t tot_sz = sizeof(cf_rc_header) + sz;
	cf_rc_header *head = malloc(tot_sz);

	head->rc = 1;
	head->sz = (uint32_t)sz;

	return head + 1;
}

void
cf_rc_free(void *p)
{
	cf_rc_header *head = (cf_rc_header *)p - 1;
	free(head);
}

int32_t
cf_rc_reserve(void *p)
{
	cf_rc_header *head = (cf_rc_header *)p - 1;
	return cf_atomic32_incr(&head->rc);
}

int32_t
cf_rc_release(void *p)
{
	cf_rc_header *head = (cf_rc_header *)p - 1;
	int32_t rc = cf_atomic32_decr(&head->rc);
	return rc;
}

int32_t
cf_rc_releaseandfree(void *p)
{
	cf_rc_header *head = (cf_rc_header *)p - 1;
	int32_t rc = cf_atomic32_decr(&head->rc);

	if (rc > 0) {
		return rc;
	}

	free(head);
	return 0;
}

int32_t
cf_rc_count(const void *p)
{
	const cf_rc_header *head = (const cf_rc_header *)p - 1;
	return (int32_t)head->rc;
}
```

**Comment by cih-y2k** [comment]
thank you @tlopatic @bbulkow
