### ISSUE TITLE
paxos_proposer_accept_send call from paxos_proposer_accept_check_retransmit incorrect

### ISSUE THREAD

**Issue by grooverdan** [aerospike/aerospike-server#196]
Firstly paxos_proposer_accept_send has no arguments and its implementation doesn't match to the provided arguments.
<pre>
fabric/clustering.c:4278:31: error: too many arguments in call to 'paxos_proposer_accept_send' [-Werror]
                                g_proposer.sequence_number);
                                                          ^
</pre>

Secondly, paxos_proposer_accept_check_retransmit holds the CLUSTERING_LOCK which paxos_proposer_accept_send also needs to acquire.

**Comment by grooverdan** [comment]
Ok. looks like this should be paxos_proposer_accept*ed*_send. Locks need to be resolved still however.

**Comment by kportertx** [comment]
The CLUSTERING_LOCK is recursive:
https://github.com/aerospike/aerospike-server/blob/master/as/src/fabric/clustering.c#L1651-L1652

The function being wrong is a problem, I am surprised that gcc with -Wall doesn't warn.

**Comment by kportertx** [comment]
Ok the it is the correct function but at some point the arguments were removed and this call was missed. It isn't an issue functionally, but will be corrected nonetheless.

Thanks.

**Comment by grooverdan** [comment]
thank you. Thanks for clarifying CLUSTERING_LOCK too.
