### ISSUE TITLE
Repo missing old branches and/or tags

### ISSUE THREAD

**Issue by jcross-linkup** [aerospike/aerospike-server#2]
It appears the aerospike-server github repo has recently been reset to some sort of blank slate.  All the old branches and/or tags for previous versions are missing.  The commit history is gone as well.  This is problematic for those of us running older versions of Aerospike before version 4.  Right now I can't upgrade past version 3.13 because I have to make code changes in order to run Aerospike server on my hardware set up.  See:
https://discuss.aerospike.com/t/fatal-error-too-many-interfaces/3581

Normally for open source projects, source tar ball is distributed with each binary release.  However, I can't seem to find such a thing.  For example, on the download page for 3.13.0.3:
https://www.aerospike.com/download/server/3.13.0.3/

There is a link to github to get the source.  However, the source for that version is not available via this repository currently.

**Comment by kportertx** [comment]
Issue addressed with [3.13.0.11](https://www.aerospike.com/download/server/notes.html#3.13.0.11).
