### ISSUE TITLE
Allow host/domain name in access-address for network configuration

### ISSUE THREAD

**Issue by mingfai** [aerospike/aerospike-server#20]
I suppose there are good reasons to use IP addresses for the other configurations, but for access-address, that is advertise to the clients for connection, it would be very nice if it allows domain/host name, so client in the same network and outside the network (connect with NAT) can connect to the same cluster at the same time. thx

**Comment by wchu-citrusleaf** [comment]
That is correct. Currently host name usage in the configuration is not supported. We have found it to be operationally more error prone to support host name.
