### ISSUE TITLE
make: *** [target/Linux-x86_64/gen/version.c] Error 1

### ISSUE THREAD

**Issue by qianghuang84** [aerospike/aerospike-server#201]
vi build/gen_version
const char aerospike_build_type[] = \"Aerospike ${EDITION^} Edition\";

has extra "^" letter cause an error.  only remove this letter.

**Comment by psi-mankoski** [comment]
The purpose and function of this character is to capitalize the edition. This feature has long been supported by Bash, which is explicitly specified in the initial "#!" line.

Can you please let us know what Bash version you are using or perhaps whether a different, more-limited shell is being invoked to run this script on your system?

Thanks.
