### ISSUE TITLE
Batch Insert / Bulk Upload

### ISSUE THREAD

**Issue by szhem** [aerospike/aerospike-server#203]
Hello guys, 

It would be really-really great if Aerospike would have Batch Insert / Bulk Upload functionality to speed up inserting data into Aerospike.

One way of implementing this feature is to ...

1. precalculate key digest for every record in the batch of records
2. determine which node is responsible for each key digest 
3. group all the records within the batch by the corresponding node (determined on the previous step) it should belong to
4. send the record groups to the corresponding nodes in one network hop

What do you think?

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit this issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
