### ISSUE TITLE
truncation sometimes leaves records behind

### ISSUE THREAD

**Issue by chiastic-security** [aerospike/aerospike-server#208]
If I pull up the latest aerospike docker container, add a couple of records with the default write policy, and then immediately truncate without setting a `lut`, it will sometimes leave the records behind.

This seems to be a race condition: adding a sleep between writing and truncation ensures that the truncation removes the records.

This is odd. I'd wondered whether it was something to do with replicating the data across nodes, but this is in a docker container, so there is presumably only one node.

The issue seems to arise only if the same client connection is used for writing and truncation. If I truncate using a different client, the truncation consistently succeeds.

**Comment by kportertx** [comment]
The truncate command doesn't wait for replication before responding to the client. This is by design, the truncate command is built on top of or SMD layer which ensures the change will replicate to all nodes eventually.

**Comment by chiastic-security** [comment]
I realise truncation is asynchronous, but even after waiting indefinitely, those records don't disappear.

**Comment by kportertx** [comment]
1. How many records are being stored on this node?
2. Are you truncating a namespace or set?
3. How are you checking if the records are still there?
4. While in this scenario, could you provide the output of
     `asadm -h SERVER_ADDRESS -e "w 1 5 show stat like truncated_records"`

**Comment by chiastic-security** [comment]
Here's how to reproduce it. This is running against the latest docker image.

`docker exec -i <container_id> aql -c "insert into test.set0 (PK, bin0) values ('key', 'val'); truncate test; select * from test"; sleep 5; docker exec -i <container_id> aql -c "select * from test"`

Sometimes it successfully truncates; sometimes it doesn't. If you add a sleep between the insertion and the pause, it always truncates successfully.

In fact, since there's only one record, truncation happens very quickly if it happens at all. If the truncation succeeds, then even the first (immediate) `select` returns `0 rows`; but when it fails, even the delayed `select` returns `1 row`.

**Comment by chiastic-security** [comment]
In answer to your Q4 (the other answers should be clear from the reproduction instructions above):

`[jamesheather@jmac ~] $ docker exec -i tender_keller asadm -e "w 1 5 show stat like truncated_records"
[ 2017-10-30 09:56:50 'show stat like truncated_records' sleep: 1.0s iteration: 1  of 5 ]
~~~~~~test Namespace Statistics~~~~~~~
NODE             :   4eb11ed31f89:3000
truncated_records:   0


[ 2017-10-30 09:56:51 'show stat like truncated_records' sleep: 1.0s iteration: 2  of 5 ]
~~~~~~test Namespace Statistics~~~~~~~
NODE             :   4eb11ed31f89:3000
truncated_records:   0


[ 2017-10-30 09:56:52 'show stat like truncated_records' sleep: 1.0s iteration: 3  of 5 ]
~~~~~~test Namespace Statistics~~~~~~~
NODE             :   4eb11ed31f89:3000
truncated_records:   0


[ 2017-10-30 09:56:53 'show stat like truncated_records' sleep: 1.0s iteration: 4  of 5 ]
~~~~~~test Namespace Statistics~~~~~~~
NODE             :   4eb11ed31f89:3000
truncated_records:   0


[ 2017-10-30 09:56:54 'show stat like truncated_records' sleep: 1.0s iteration: 5  of 5 ]
~~~~~~test Namespace Statistics~~~~~~~
NODE             :   4eb11ed31f89:3000
truncated_records:   0`

**Comment by kportertx** [comment]
Thanks for your investigation. We were able to reproduce this as well. We also determined that this is by design. The truncate operation has a resolution of 1 millisecond and any writes that occur within the same millisecond are not deleted. This is to protect writes that occur after the truncate command, but also within the same millisecond, from being deleted.

**Comment by chiastic-security** [comment]
Thanks. So sleeping for a few milliseconds before truncation should solve the problem?

**Comment by kportertx** [comment]
A millisecond sleep should cause this test to succeed.
