### ISSUE TITLE
Iterate bins in Lua UDF

### ISSUE THREAD

**Issue by mullanaphy** [aerospike/aerospike-server#21]
Right now it seems Lua directly accesses the memory locations of the bin data for UDFs yet there is no way to iterator over all the bins inside of a record. This is something that's pretty much needed in my company's use case where we don't know exactly what each bin is in a record since they are dynamically built to be a key like "YYMMDDDD:someFlag" so right now to delete these old keys every day we need something to scan the collection and delete any key that is "YYMMDDDD:*" < today. If there was a way to iterate the bins via Lua then the code could greatly be simplified and wouldn't need to worry about accidentally missing a day here or there if one of the cron processes silently fail.

**Comment by wchu-citrusleaf** [comment]
This is released in 3.3.19
