### ISSUE TITLE
How to horizontally add cluster nodes and modify configuration files to restart each service in the cluster without being affected

### ISSUE THREAD

**Issue by jclivi** [aerospike/aerospike-server#21]
How to restart cluster services without being affected

1. Configuration before horizontal expansion:
  
  heartbeat {
        mode mesh
        address 192.168.127.128
        port 3002
        #all cluster
        mesh-seed-address-port 192.168.127.128 3002
        mesh-seed-address-port 192.168.127.131 3002

        # aerospike_mesh.conf for alternative.
        interval 150
        timeout 10      
        }

2. Configuration after horizontal expansion:

  heartbeat {
        mode mesh
        address 192.168.127.132
        port 3002
        #all cluster
        mesh-seed-address-port 192.168.127.132 3002
        mesh-seed-address-port 192.168.127.128 3002
        mesh-seed-address-port 192.168.127.131 3002

        # aerospike_mesh.conf for alternative.
        interval 150
        timeout 10      
        }

**Comment by kportertx** [comment]
I see that you've received response to a duplicate question posted to the GO client: https://github.com/aerospike/aerospike-client-go/issues/327.

In the future please post questions to the community forums at [discuss.aerospike.com](http://discuss.aerospike.com). We use GitHub issues for bug/deficiency reports.

Thanks.
