### ISSUE TITLE
Wrong file name of aerospike tools in documentation

### ISSUE THREAD

**Issue by alexradzin** [aerospike/aerospike-server#211]
The tgz file is referenced incorrectly in [document that describes how to install the aerospike tools](https://www.aerospike.com/docs/operations/install/tools/ubuntu). 

Compare the following lines:

`wget -O aerospike.tgz 'https://www.aerospike.com/download/tools/latest/artifact/ubuntu12'`

and 

`tar -xvf aerospike-tools.tgz`

The file is downloaded as `aerospike.tgz` and extracted as `aerospike-tools.tgz`. It seems that the line of `wget ...` was copied from the aerospike server installation instructions.

**Comment by mcoberly2** [comment]
Hello Alexander,
Thanks for pointing out the typo in our Tools Install documentation.
The documentation has been updated for ubuntu & debian.
It is expected to be published to our website within the next few days.
