### ISSUE TITLE
aerospike-server tries to build jemalloc even though the allocatior is already jemalloc 

### ISSUE THREAD

**Issue by yurivict** [aerospike/aerospike-server#22]
On FreeBSD the allocator is already jemalloc, but ```aerospike-server``` tries to build it again.

**Comment by kportertx** [comment]
> On FreeBSD

Currently, Aerospike only supports Linux.

> the allocator is already jemalloc

I believe this wouldn't matter since we rely on a particular version of jemalloc's APIs for various aspects of the server's memory inspection toolkit.
