### ISSUE TITLE
Vault integration breaks with 5.6.0.3

### ISSUE THREAD

**Issue by ncabatoff** [aerospike/aerospike-server#25]
_________

**Aerospike version:** *Put your Aerospike release version or `git describe --long --all` output here. For example: "3.15.0.1, heads/master-0-g450aee1"*

Docker 5.6.0.3

**Client version:** *Put which client and the version of the client you are using (if applicable) here. For example: "Java 4.0.8, C 4.2.0"

```
$ grep aerospike go.mod
        github.com/aerospike/aerospike-client-go v3.1.1+incompatible
```
__________

*Explain your _Aerospike Server_ issue in detail here and (if applicable) provide logs snippets, configuration, and/or reproduction instructions.*

The Vault tests for validating Aerospike as a storage backend started failing today.  These tests use the "latest" docker image tag, and they fail in the same way when I tried changing the tag to be 5.6.0.3. Changing the tag to 5.5.0.10 makes the tests pass again, as I did in https://github.com/hashicorp/vault/pull/11677.

I'm not familiar with the integration internals, so I'm afraid I can't give much more detail than this.  An example failure is here: https://app.circleci.com/pipelines/github/hashicorp/vault/17659/workflows/d4f404a5-b4b5-4aac-996f-d77007fe2b64/jobs/208122/tests#failed-test-0

which contains:
```
=== RUN   TestAerospikeBackend
    aerospike_test.go:31: initial list failed: Node BB9040012AC4202 172.18.0.4:3000: Unsupported Server Feature
--- FAIL: TestAerospikeBackend (8.71s)
```

The integration is here: https://github.com/hashicorp/vault/blob/master/physical/aerospike/aerospike.go
And the test failure is here: https://github.com/hashicorp/vault/blob/master/sdk/physical/testing.go#L15

**Comment by rbotzer** [comment]
@reugn this is about the Aerospike as a Backend Storage integration for Vault.

**Comment by reugn** [comment]
https://github.com/hashicorp/vault/pull/12165
