### ISSUE TITLE
What is the difference between the enterprise version of the source code?

### ISSUE THREAD

**Issue by fantastic2085** [aerospike/aerospike-server#26]
Please direct the following to our [community forum](https://discuss.aerospike.com/):
- general questions
- help requests
- feature requests
- non Aerospike Server issues

The issues submitted here should be Aerospike Server **code** related. Examples include:
- crashes (please provide stack trace from logs)
- bugs (not behaving as expected/documented)
- code quality

__________

**OS:** *Put your operating system here. For example: "Ubuntu 16.10", "CentOS 7", "Debian 8" etc.*

**Aerospike version:** *Put your Aerospike release version or `git describe --long --all` output here. For example: "3.15.0.1, heads/master-0-g450aee1"*

**Client version:** *Put which client and the version of the client you are using (if applicable) here. For example: "Java 4.0.8, C 4.2.0"

__________

*Explain your _Aerospike Server_ issue in detail here and (if applicable) provide logs snippets, configuration, and/or reproduction instructions.*

**Comment by kportertx** [comment]
Summary of the Enterprise features can be found here:

https://aerospike.com/products/product-matrix/
