### ISSUE TITLE
How to compile aerospike without jemalloc?

### ISSUE THREAD

**Issue by zouyonghao** [aerospike/aerospike-server#29]
USE_JEM=0 did not take effect...

I do not want to use jemalloc because I can not compile aerospike with ASan, and it seems a jemalloc issue.

**Comment by laurynas-biveinis** [comment]
Please review and adjust for your needs the attached patch.
[asan-experimental.patch.txt](https://github.com/aerospike/aerospike-server/files/6631579/asan-experimental.patch.txt)

Please note that it uses `#ifdef __SANITIZE_ADDRESS__` for ASan compilation detection, which works with GCC only. If you are using clang, you will have to rewrite those checks to `#if __has_feature(address_sanitizer)` instead.

**Comment by zouyonghao** [comment]
Thanks @laurynas-biveinis .
I successfully compile aerospike using `make USE_LUAJIT=0 CC="clang-9 -fsanitize=address"` after patching the `alloc.c` with part of your patch.
I replace macros with `#if !__has_feature(address_sanitizer)` and modify some Makefiles with deleting some `-Wall` options.
