### ISSUE TITLE
Missing cf_queue_priority.h while make aerospike-server-master in CentOS7.5

### ISSUE THREAD

**Issue by GogoChiefs** [aerospike/aerospike-server#32]
Please direct the following to our [community forum](https://discuss.aerospike.com/):
- help requests

The issues submitted here should be Aerospike Server **code** related. Examples include:
- crashes (please provide stack trace from logs)
- bugs (not behaving as expected/documented)
- code quality

__________

**OS:** *"CentOS 7.5"*

**Aerospike version:** * " 5.2.0.32"*

__________

Hello,
An error came out when I exec make in Aerospike-server-master，../include/sindex/job_manager.h:30:42: fatal error: citrusleaf/cf_queue_priority.h: No such file or directory.
I download Aerospike-server-masterand all modules from GitHub ，when I Run make command，one error came out:
make -C as make[1]: Entering directory/opt/aerospike-server-master/as'
make -C src all
make[2]: Entering directory /opt/aerospike-server-master/as/src' cc -gdwarf-4 -g3 -O3 -fno-common -fno-strict-aliasing -Wall -D_FILE_OFFSET_BITS=64 -std=gnu99 -D_REENTRANT -D_GNU_SOURCE -DENHANCED_ALLOC -march=nocona -MMD -Werror -DMARCH_x86_64 -D__FILENAME__=\"job_manager.c\" -o ../../target/Linux-x86_64/obj/sindex/job_manager.o -c -I../include -I../../target/Linux-x86_64/gen -I/opt/aerospike-server-master/cf/include -I/opt/aerospike-server-master/ai/include -I/opt/aerospike-server-master/modules/common/target/Linux-x86_64/include -I/opt/aerospike-server-master/modules/jansson/src -I/opt/aerospike-server-master/modules/mod-lua/target/Linux-x86_64/include -I/opt/aerospike-server-master/modules/s2-geometry-library/geometry -I/opt/aerospike-server-master/modules/luajit/src sindex/job_manager.c In file included from sindex/job_manager.c:27:0: ../include/sindex/job_manager.h:30:42: fatal error: citrusleaf/cf_queue_priority.h: No such file or directory #include "citrusleaf/cf_queue_priority.h" ^ compilation terminated. make[2]: *** [../../target/Linux-x86_64/obj/sindex/job_manager.o] Error 1 make[2]: Leaving directory /opt/aerospike-server-master/as/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory /opt/aerospike-server-master/as' make: *** [all] Error 2 
Is there someone can help me??? :D

**Comment by kportertx** [comment]
Did you pull in the submodules as mentioned herehttps://github.com/aerospike/aerospike-server/#submodules?
