### ISSUE TITLE
Is it legal to modify / bypass limitations (eg. maximum 8 nodes) in the source codes ?

### ISSUE THREAD

**Issue by kevx** [aerospike/aerospike-server#34]
I am wondering if it's legal to do so.
Thanks.

**Comment by kportertx** [comment]
Sorry, developers monitoring these issues are not qualified legal experts and will not answer legal questions.

**Comment by itsnikolayy** [comment]
I don't see anything in the license that says you can't upon a first look, but I find it odd to have an open source edition that you can compile that still has limitations written in. I would have assumed it would only apply to the precompiled binaries.
