### ISSUE TITLE
init script lacks LSB headers

### ISSUE THREAD

**Issue by elreydetodo** [aerospike/aerospike-server#35]
I'm running Fedora 21 using the Aerospike Server package for RHEL6. I know it's not supported, but wait! It works *almost perfectly*. The only caveat is that Fedora (because it is systemd-based), REALLY wants proper LSB-compliant heads in systvinit scripts. Otherwise, the Aerospike service ends up starting before my network is up, and the result is that the Aerospike server doesn't bind to any useful interfaces.

The fix for this is easy. Add this to the top of the init script:
```bash
### BEGIN INIT INFO
# Description: Starts and stops the Aerospike daemon
# Default-Start: 3 4 5
# Required-Start: $network
### END INIT INFO
```

Fedora has a complete writeup of producing systemd-compatible sysvinit scripts here:
http://fedoraproject.org/wiki/Packaging:SysVInitScript

There are several other headers you could include, but really the instruction to wait in $network is the most important thing. This should not adversely affect the init script functioning in RHEL.

**Comment by candrews** [comment]
In addition to fixing the sysvinit script, should systemd service definitions also be provided, packaged, and used going forward (instead of sysvinit) on systemd distros (such as Fedora)? (This should probably be reported as a separate issue)

**Comment by psi-mankoski** [comment]
Thanks for the issue reports. We have updates to the server init. scripts (including "systemd" support) in the works. We'll let you know when it's available so you can test it and give feedback on how it works on your favorite distros. We appreciate your help verifying that the software works correctly across distros. and configurations we may not have tested yet ourselves.

**Comment by psi-mankoski** [comment]
Fixed in the development mainline.
