### ISSUE TITLE
aerospike_telemetry.service is marked executable

### ISSUE THREAD

**Issue by ghost** [aerospike/aerospike-server#36]
**OS:** CentOS 7

**Aerospike version:** 5.4.0.1  (code shows problem still exists in 5.7.0.10)
__________
journalctl shows the following message about 6 times/day:
`systemd[1]: Configuration file /usr/lib/systemd/system/aerospike_telemetry.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

line 80 of `pkg/rpm/Makefile` shows the problem:
`install -pm 755 $(DEPTH)/as/etc/aerospike_telemetry.service $(BUILD_ROOT)/usr/lib/systemd/system/aerospike_telemetry.service`

(`pkg/rpm/Makefile` in 5.4.0.1 is identical to 5.7.0.10)

**Comment by kportertx** [comment]
Thanks for bringing this to our attention - it will be addressed in the next release.
