### ISSUE TITLE
Unable to install Aerospike on Macbook M1 Pro while using ubuntu Vm

### ISSUE THREAD

**Issue by harshavallamkonda9** [aerospike/aerospike-server#37]
Hey Team. 

So I have purchased this new MacBook Pro with Apple M1 Pro chipset and have installed UTM software to run Ubuntu 20.04 but when i try to install aerospike it is showing amd64 error...So any solution?

**Comment by kportertx** [comment]
There are a few issue tickets discussing lack of ARM support making this one redundant to #19. Good news is that ARM support is the primary focus of 6.2.

**Comment by kportertx** [comment]
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0
