### ISSUE TITLE
Include Ubuntu 22.04 LTS package into release

### ISSUE THREAD

**Issue by agolovenko** [aerospike/aerospike-server#38]
Hi guys! Since Ubuntu 22.04 LTS is already out, could you please include the package for it?

**Comment by pushshift** [comment]
Is there any update on this? We would love to evaluate Aerospike but we are currently unable to locate any installation media for Ubuntu 22.04. Will Aerospike support Ubuntu 22.04 soon? Is it possible to use 20.04 community installation for the time being? We did try that but ran into errors when trying to start the service. 

Thanks!

**Comment by kportertx** [comment]
The move to OpenSSL 3 is a bit tricky since we have to continue to support OpenSSL 1.1.1 for fips.

This won't be a focus for 6.2 as the team is focused on ARM support for this release, but possibly in the subsequent release.

**Comment by kportertx** [comment]
The upcoming 6.3 release will include support for Ubuntu 22.04.
