### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [aerospike/aerospike-server#39]
Hi!

I am reading the documentation and cannot find the information about supported combinations of OS-Hardware Architcture. Is there any? I only see a set of prebuilt binaries per release. But for the users will be much easier to get the information about the support status (and different support levels for each) from the documentation.

Maybe some kind of table or something like that will be a good start.

Thanks in advance!

**Comment by kportertx** [comment]
The distros/architectures we release packages for are the ones we test on and therefore the ones we support. It is uncommon but we have seen distro specific bugs in the past, the most recent was specific to Ubuntu 16.04.

Also note that we currently only support X86_64. Aerospike 6.2 will add aarch64 support.
