### ISSUE TITLE
Auto build & run tests using Travis?

### ISSUE THREAD

**Issue by simonhf** [aerospike/aerospike-server#4]
How about auto building and testing the github repo via Travis [1]? It's free for open source projects :-) See [2] for an example usage. You can even embed a little icon in the README.md showing whether the build and test was successful or not. -- Simon

[1] https://travis-ci.org/
[2] https://github.com/simonhf/sharedhashfile

**Comment by shakthimaan** [comment]
What tools or framework is used in the test suite?
