### ISSUE TITLE
non-x86 platforms - no _mm_prefetch

### ISSUE THREAD

**Issue by grooverdan** [aerospike/aerospike-server#4]
ubuntu-18.04 ppc64le - git master @ c302133

in as/src/base/index.c, _mm_prefetch, defined by the include header <xmmintrin.h> is arch specific.

Using a generic gcc builtin would make this more portable:
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005fprefetch

**Comment by grooverdan** [comment]
:snail:

**Comment by kportertx** [comment]
This will be addressed in 6.2 to support ARM. This ticket is now effectively a duplicate of #19.

**Comment by kportertx** [comment]
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0
