### ISSUE TITLE
can not install aerospike-tools

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#40]
sudo ./asinstall 
Installing tools
rpm -Uvh aerospike-tools-3.4.1-1.el6.x86_64.rpm
error: Failed dependencies:
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by aerospike-tools-3.4.1-1.el6.x86_64
Installing server
rpm -Uvh aerospike-server-community-3.4.1-1.el6.x86_64.rpm
Preparing...                ########################################### [100%]
	package aerospike-server-community-3.4.1-1.el6.x86_64 is already installed

But  libcrypto.so.10 indeed existed in /usr/lib64

**Comment by psi-mankoski** [comment]
The short answer is that the issue will likely be resolved if you update your "openssl" package:

     $ sudo yum update openssl

The longer answer is that the RPM system permits the same library to be provided by multiple modules, as well as for multiple architectures, and the module name is used by RPM for dependency resolution. The module name is listed within parentheses (i.e., it is also "libcrypto.so.10", for x86_64, in the message you received.) You can see what is actually installed on your system using:

     $ repoquery -i --provides openssl | grep libcrypto.so.10
     libcrypto.so.10
     libcrypto.so.10(OPENSSL_1.0.1)
     libcrypto.so.10(OPENSSL_1.0.1_EC)
     libcrypto.so.10(libcrypto.so.10)
     libcrypto.so.10()(64bit)
     libcrypto.so.10(OPENSSL_1.0.1)(64bit)
     libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
     libcrypto.so.10(libcrypto.so.10)(64bit)

If there isn't a full \<Library>(\<Module>)(\<Architecture>) match, then the "rpm" install command will fail. (If the installed library's architecture is correct, however, then installing manually using the "rpm" option "--nodeps" could be an alternative work-around.)

What specific Linux distribution and version are you using? Could you send the output of the "repoquery" command?

More details regarding a similar problem and the similar recommended fix can be found at:
http://stackoverflow.com/questions/20518183/dependency-resolution-fails-on-installed-library
