### ISSUE TITLE
Can not create RPM installer on CentOS 7

### ISSUE THREAD

**Issue by vit1251** [aerospike/aerospike-server#42]
I type shell command on CentOS 7 in Digital Ocean cloud VM:

> # make rpm

And result is 

> sed -i 's/@RELEASE@/'Unknown redhat version 7.'/g' /opt/aerospike-server/pkg/rpm/aerospike.spec
> sed: -e expression #1, char 19: unterminated `s' command
> make[1]: *** [package] Error 1
> make[1]: Leaving directory `/opt/aerospike-server/pkg/rpm'
> make: *** [rpm] Error 2

**Comment by psi-mankoski** [comment]
Thanks for the issue report! I have reproduced this problem, and we are working on full CentOS 7 support, including building RPMs.

**Comment by psi-mankoski** [comment]
This issue has been corrected in our development version and the fix will be included in the next release.
