### ISSUE TITLE
lstack.filter throws an error

### ISSUE THREAD

**Issue by ttrifonov** [aerospike/aerospike-server#43]
Here is an example:

```
aql> execute lstack.filter('autoid', 50) on logs.time-index where pk='demo'

Error: (100) /opt/aerospike/sys/udf/lua/ldt/ldt_common.lua:1261: 1422:LDT-Sub Record Open Error
```

I don't know what is wrong with the sub-record, but anyway this should silently fail. Unfortunately, I find the LSTACK quite unstable for use... So bad, otherwise it looked as a promising thing. It seems the server has inserted bad data in the lstack, as I haven't modified it after insertion.

**Comment by citrusraj** [comment]
Do you see any other error preceding this one ... in the server logs. 

If you could please give be steps to reproduce this problem. I tried this and did not see the problem show up ... 

1. Pushed around 10000 items into LSTACK of size ~= 1k
2. Peek with filter to fetch few values using filter ... 

-- R

**Comment by ttrifonov** [comment]
I'll look in the logs, but meanwhile - is it possible that the problem occurred in the previous versions of  Aerospike servers? I've updated today with the latest version, but the server was with a version about 1 month old?
I use a custom settings on the list:

```
function userModule.adjust_settings( ldtMap )
  local ldt_settings=require('ldt/settings_lstack');
  ldt_settings.use_package( ldtMap, "ListMediumObject" );

  ldt_settings.set_store_limit( ldtMap, 10000 )

  ldt_settings.set_ldr_entry_count_max( ldtMap, 10000 )

  ldt_settings.set_coldlist_max( ldtMap, 200 )
  ldt_settings.set_colddir_rec_max( ldtMap, 10000 )
end
```

Is it possible that this config is wrong ? Also, this is a development server, and I've made some tests with directly modifying the default settings in `ldt/settings_lstack`. After updating to new version, the settings probably were overwritten, so is it possible the problem to be that a record is created with different list settings than at the time it is being read? I still try to understand how the llist/lstack thing work, and maybe I've made something wrong, but is it possible that such errors to fail silently? I guess I have some corrupted element in the stack, but cannot remove it(pop-ing from Stack would be useful here).

**Comment by citrusraj** [comment]
>> but is it possible that such errors to fail silently?

This is not supposed to go away silently :)

Config looks ok to me but may be running with two different config could have possibly created problems for the server. Did you see any operation failing which could possibly have left some stale subRecord pointer hanging around ... 

You are at 3.4.1 ??

**Comment by ttrifonov** [comment]
Here is an Error from the logs:

```
/var/log/aerospike/aerospike.log-20150214.gz:Feb 13 2015 17:03:28 GMT: WARNING (udf): (/opt/aerospike/sys/udf/lua/ldt/ldt_common.lua::1068) [ERROR] ldt_common_2014_11_25.A:createAndInitESR()> Problems Creating ESR
```

But this was with 3.4.0. I've updated on 13-Feb to 3.4.1, and these errors stopped. Then I also deleted the whole set and re-created it again, so no data was inserted in the set from 3.4.0. So something was inserted in the lstack after 13 Feb. Today I've updated to 3.5.2, and I still see these errors.

Here is the only WARNING/ERROR I've found in the logs so far:


```
/var/log/aerospike/aerospike.log-20150217.gz:Feb 16 2015 12:57:24 GMT: WARNING (udf): (/opt/aerospike/sys/udf/lua/ldt/lib_lstack.lua::1752) [ERROR] ldt_common_2014_12_20.A:openSubRec()> SubRec Open Failure: Digest(69 4F 7D DA D6 B0 23 0F 72 18 E7 00 34 31 00 00 00 00 00 00)```

**Comment by birkirb** [comment]
I'm also getting this, on 3.5.4:

````
 /opt/aerospike/sys/udf/lua/ldt/ldt_common.lua:1261: 1422:LDT-Sub Record Open Error
````

Looks like this in the log:

````
Mar 20 2015 12:13:50 GMT: INFO (ldt): (ldt_aerospike.c::750) 69 E4 FE 61 4F EC FF 11 09 53 2A D0 10 A9 00 00 00 00 00 00 Failed to open Sub Record rv=-3 241355648701375<Digest>:0x69e4fe614fecff1109532ad010a9db82fdb493bf
Mar 20 2015 12:13:50 GMT: INFO (ldt): (ldt_aerospike.c::750) DA EE 11 44 F2 25 39 11 2D 56 51 EE BD AB 00 00 00 00 00 00 Failed to open Sub Record rv=-3 241353814074129<Digest>:0xdaee1144f22539112d5651eebdabdb82905a6311
Mar 20 2015 12:13:50 GMT: WARNING (udf): (/opt/aerospike/sys/udf/lua/ldt/lib_lstack.lua::2205) [ERROR]<ldt_common_2014_12_20.A:openSubRec()> SubRec Open Failure: Digest(69 E4 FE 61 4F EC FF 11 09 53 2A D0 10 A9 00 00 00 00 00 00)
Mar 20 2015 12:13:50 GMT: WARNING (udf): (/opt/aerospike/sys/udf/lua/ldt/lib_lstack.lua::2205) [ERROR]<ldt_common_2014_12_20.A:openSubRec()> SubRec Open Failure: Digest(DA EE 11 44 F2 25 39 11 2D 56 51 EE BD AB 00 00 00 00 00 00)
Mar 20 2015 12:13:50 GMT: INFO (ldt): (ldt_aerospike.c::750) 1A 9D E1 F5 CB B7 93 11 9B F5 7B B0 ED B2 00 00 00 00 00 00 Failed to open Sub Record rv=-3 241354531514231<Digest>:0x1a9de1f5cbb793119bf57bb0edb2db82bb1da777
Mar 20 2015 12:13:50 GMT: WARNING (udf): (/opt/aerospike/sys/udf/lua/ldt/lib_lstack.lua::2205) [ERROR]<ldt_common_2014_12_20.A:openSubRec()> SubRec Open Failure: Digest(1A 9D E1 F5 CB B7 93 11 9B F5 7B B0 ED B2 00 00 00 00 00 00)
````

I saw something in the release notes about LSTACK being deprecated, I guess it was moved from native to LUA scripts or something? Should it be considered as not stable for production use?

**Comment by wchu-citrusleaf** [comment]
We have consolidated LDT data type to LLIST and deprecated lset, lmap, and lstack. Server version 3.5.8 and above also has major fixes for LLIST. Please take the latest version for a spin.
