### ISSUE TITLE
Can't bind aerospike server to localhost

### ISSUE THREAD

**Issue by ook** [aerospike/aerospike-server#44]
_Version_: Aerospike Community Edition build 3.4.1

_Level_: configuration

# What I want to do:

Bind ASD to localhost on a hosted dedicated box, so my node is not exposed to the internet. The clients will use a ssh tunnel (details in [this post](http://blog.ookook.fr/2015/02/21/aerospike-community-secured)).

Here my network configuration block: 

```
network {
        service {
                address any

                port 3000
                reuse-address
                network-interface-name lo
        }

        heartbeat {
                mode multicast
                address 239.1.99.222
                port 9918

                # To use unicast-mesh heartbeats, comment out the 3 lines above and
                # use the following 4 lines instead.
#               mode mesh
#               port 3002
#               mesh-address 10.1.1.1
#               mesh-port 3002

                interval 150
                timeout 10
        }

        fabric {
                port 3001
        }

        info {
                port 3003
        }
}
```

# What I see:

asd respond on `lo`… but also on `eth0`.

# What I guess:

The directive `network-interface-name` doesn't honor its reference description ["The name of the interface to attach to"](http://www.aerospike.com/docs/reference/configuration/#network-interface-name)

I'm pretty sure it's a bug. Feel free to require more details.

Thomas Lecavelier

**Comment by sunilvirus** [comment]
Bug or not, I definitely agree that the rules here are a bit complex. In simple terms, the solution to the problem will be as follows.

network {
        service {
                address 127.0.0.1
                port 3000
                reuse-address
                access-address 127.0.0.1 virtual
        }
...


To go into the details...
1. **"network-interface-name"** is used to generate nodeid as well as pick the IP address which is used for heartbeats in case of mes (obviously this is not used in multicast). Note: this IP is not used to publish as service address to the node's neighbors.
2. **"access-address"** is what you want to advertise as service address to your neighbors (and indirectly to your clients). should say 'virtual' if its a virtual address (Note: 127.0.0.1 is virtual).
3. **"address"** is used to listen on a particular IP. "any" means all interfaces. This is the way to limit listening on a single interface. when anything other than 'any' is used, it is used as **"access-address"** automatically

**Comment by ook** [comment]
I get it, and it make sense.

Checked your configuration snippet: work great. Respond on localhost but not on public address.
Thank you: now my communication is securised and private. Perfect setup to test a single node.

**Comment by sunilvirus** [comment]
@ook , Thank you.

**Comment by WhiteTrashLord** [comment]
With this config only localhost listens on port 3000. But all other interfaces listen on ports 3001 and 3003. It must be a bug!

network {
	service {
		address 127.0.0.1
		port 3000
		reuse-address
		access-address 127.0.0.1 virtual
		
	}

	heartbeat {
		mode multicast
		address x.x.x.x
		port 9918

		# To use unicast-mesh heartbeats, remove the 3 lines above, and see
		# aerospike_mesh.conf for alternative.

		interval 150
		timeout 10
	}

	fabric {
	    address 127.0.0.1
		port 3001		
	}

	info {
		address 127.0.0.1
		port 3003
	}
}
