### ISSUE TITLE
write delete is buggy in v3.5.3

### ISSUE THREAD

**Issue by imkira** [aerospike/aerospike-server#45]
It appears a bug was introduced in v3.5.3 related to generation checking and deletion (write_delete) of bins.

Suppose I have the following program (and for simplicity that there is only one client running):

1. get a record
2. write a bin to it using the generation I obtained in step 1 (or use generation 0 if there was no record)
3. get the record again
4. delete the bin with the generation I obtained in step 3

If I do this in v3.5.2, the program works properly.
If I do this in v3.5.3, the program breaks in step 4 with a ```Generation error```.

I made a reduced test case reproducing this issue:

http://play.golang.org/p/gdJSwIbVCQ

I checked the changelog to try to understand what the issue was.
At first I compared what happened in between the two versions at

https://github.com/aerospike/aerospike-server/compare/3.5.2...3.5.3 

looked at

>>> KVS - AER-1376 - Add generation enforcement option for record deletion.

https://github.com/aerospike/aerospike-server/commit/46ccfcff45ea99e83050211f80cd67c8bf36d268#diff-d0042353e74b16d8776db46169f0eb57R2905

and I thought this might be cause of the problem.

The worst thing is that after the program breaks in step 4, the record appears to be deleted and to leave the database in an inconsistent state. I say this because when I try to execute the program again it always returns no record in step 1 but fails in step 2 with a ```Generation error```. Right after the failure at step 2 I notice:

>>> WARNING (rw): (thr_rw.c::5709) as_record_get: expired record still in system, no read: n_bins(0)

in the log file.
So the record "disappears magically" after "apparently" not being able to delete it in step 4.

What I am saying is, although ```write_delete_local``` returns 

https://github.com/aerospike/aerospike-server/commit/46ccfcff45ea99e83050211f80cd67c8bf36d268#diff-d0042353e74b16d8776db46169f0eb57R2936

with a generation error (which is a CAS check) should not, in any circumstance, leave the database in an inconsistent state but it appears to do so.

**Comment by imkira** [comment]
I just noticed that although consecutive runs of the program always stop in step 2 with a generation error, if I restart aerospike and run the program again it first stops in step 4 and then starts stopping in step 2 for consecutive runs.
So this appears to be causing some internal inconsistency (in memory and not in storage).

**Comment by wchu-citrusleaf** [comment]
Thanks. We realized this is indeed a newly introduced bug, which has to do with deleting the last bin in the record, which should remove the record.

Fix will be on it's way.

**Comment by imkira** [comment]
I am assuming this is fixed in 3.5.4:

KVS - Issue#45/AER-3395 - Only apply delete generation check if delete is direct from client.

I am testing it and as soon as I confirm the fix I will close this issue.
Thanks a lot!

**Comment by imkira** [comment]
Working nicely ;)
Thanks a lot for the support
