### ISSUE TITLE
Fabric should support TCP Keepalive

### ISSUE THREAD

**Issue by Mmmkayness** [aerospike/aerospike-server#46]
We've been recently evaluating Aerospike over multiple cloud environments (AWS and GCE) and spotted an issue whereby clients can fail to write to the Aerospike cluster in Google Compute Engine if the cluster has been idle for more than 10 minutes (idle meaning that no clients have been reading or writing). 

This phenomenon looks to be caused by Google Compute Engine proactively reaping idle TCP connections https://cloud.google.com/compute/docs/troubleshooting#communicatewithinternet and their advice is to configure sensible heartbeat parameters in the kernel to keep long lived TCP connections alive.

Fabric, by design, doesn't do anything when no data is being read or written (at least, observed via tcpdump), except for passing details of other nodes on cluster formation. Since those connections are established on startup, they are candidates to be reaped by GCE without Aerospike realising it. This can be observed by attempting to write to the cluster over 10 minutes after formation, whereby the TCP Send-Q will continually grow for those 'ESTABLISHED' Fabric connections.

This kind of behaviour may be present in other network environments depending on firewall configuration, so there should be a general solution to the problem.

I am no C programmer myself, so I can't provide an elegant pull request, but I did run a simple test on Aerospike with SO_KEEPALIVE (via SOL_SOCKET) set for Fabric connections (after TCP_NODELAY is set).
``` c
int flag = 1;
setsockopt(fb->fd, SOL_SOCKET, SO_KEEPALIVE, &flag, sizeof(flag) );
```

I repeated the same process of forming a cluster and waiting over 10 minutes. This time the keepalives ensured that GCE did not reap connections, and I saw no exceptions in client writes. 

A solution to this may wish to expose keepalive parameters in aerospike fabric config (using SOL_TCP) or simply support the globally set parameters in sysctl.

**Comment by psi-mankoski** [comment]
Thanks for the issue report. We have begun discussing this internally, and before moving forward with a particular solution, I have some questions.

Could you please tell us what exactly you observe happening in the Aerospike cluster left idle for >10 min. in GCE? Logs and/or stack traces would be very helpful for us to replicate what you are seeing.

Thanks!

**Comment by Mmmkayness** [comment]
Hi sure,

So during idle conditions, there are no packets sent over fabric ports, which can be observed via tcpdump -vvv port 3001. There are no cleanup operations on the connections either, so the fabric connections remain ESTABLISHED and unused.

I have a 2 node setup, and each node has established 2 fabric connections to each other:
```
as01
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24883/asd       
tcp        0      0 10.240.136.123:45751    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:45752    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39940      ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39939      ESTABLISHED 24883/asd      
```

and

```
as02
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45751    ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:39939      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:39940      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45752    ESTABLISHED 24249/asd    
```
At this point their TCP buffers are empty. I then left the cluster for an hour and observed that the same state still exists. After this I attempted a put from ascli:
```ascli put test foo 1 '{ "example": [1234567] }' ```

The first write appeared to succeed without issue and I can issue a get on either server to retrieve the key. Netstat however shows that both servers have data waiting in their Send-Q:
```
as01
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24883/asd       
tcp        0    187 10.240.136.123:45751    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0    135 10.240.136.123:45752    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39940      ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39939      ESTABLISHED 24883/asd       
```

```
as02
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45751    ESTABLISHED 24249/asd       
tcp        0     65 10.240.135.8:39939      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0    171 10.240.135.8:39940      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45752    ESTABLISHED 24249/asd       
```

I then perform a second put, to a new key and this time I receive an error in the client:
```ERROR 9 Client timeout: timeout=1000 iterations=1 failedNodes=0 failedConns=0```

This repeats on every put and I can see that the Send-Q on just the server I am issuing the ascli commands only continues to increase:

```
as01
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24883/asd       
tcp        0    545 10.240.136.123:45751    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0    509 10.240.136.123:45752    10.240.135.8:3001       ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39940      ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39939      ESTABLISHED 24883/asd      
```

```
as02
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45751    ESTABLISHED 24249/asd       
tcp        0     65 10.240.135.8:39939      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0    171 10.240.135.8:39940      10.240.136.123:3001     ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45752    ESTABLISHED 24249/asd    
```

There's nothing I can discern much from the aerospike logs but we can see that as01 has made several master writes:
```
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4580)  system memory: free 53570968kb ( 99 percent free ) 
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4588)  migrates in progress ( 0 , 0 ) ::: ClusterSize 2 ::: objects 2 ::: sub_objects 0
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4596)  rec refs 2 ::: rec locks 0 ::: trees 0 ::: wr reqs 0 ::: mig tx 0 ::: mig rx 0
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4602)  replica errs :: null 0 non-null 0 ::: sync copy errs :: node 0 :: master 0 
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4612)    trans_in_progress: wr 0 prox 0 wait 0 ::: q 0 ::: bq 0 ::: iq 0 ::: dq 0 : fds - proto (0, 52, 52) : hb (2, 2, 0) : fab (20, 20, 0)
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4614)    heartbeat_received: self 0 : foreign 101354
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4615)    heartbeat_stats: bt 0 bf 76718 nt 0 ni 0 nn 0 nnir 0 nal 0 sf1 0 sf2 0 sf3 0 sf4 0 sf5 0 sf6 0 mrf 0 eh 0 efd 0 efa 0 um 0 mcf 0 rc 0 
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4628)    tree_counts: nsup 0 scan 0 batch 0 dup 0 wprocess 0 migrx 0 migtx 0 ssdr 0 ssdw 0 rw 0
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4644) namespace test: disk inuse: 0 memory inuse: 150 (bytes) sindex memory inuse: 0 (bytes) avail pct 100
Mar 11 2015 12:26:51 GMT: INFO (info): (thr_info.c::4689)    partitions: actual 2034 sync 2062 desync 0 zombie 0 wait 0 absent 0
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: reads (4 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::163)  (00: 0000000004)
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: writes_master (3 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::163)  (11: 0000000003)
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: proxy (1 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::163)  (03: 0000000001)
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: writes_reply (0 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: udf (0 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: query (0 total) msec
Mar 11 2015 12:26:51 GMT: INFO (info): (hist.c::137) histogram dump: query_rec_count (0 total) count
```

And on as02 (the replica for the write as only stored 1 object):
```
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4580)  system memory: free 53594696kb ( 99 percent free ) 
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4588)  migrates in progress ( 0 , 0 ) ::: ClusterSize 2 ::: objects 2 ::: sub_objects 0
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4596)  rec refs 2 ::: rec locks 0 ::: trees 0 ::: wr reqs 0 ::: mig tx 0 ::: mig rx 0
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4602)  replica errs :: null 0 non-null 0 ::: sync copy errs :: node 0 :: master 0 
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4612)    trans_in_progress: wr 0 prox 0 wait 0 ::: q 0 ::: bq 0 ::: iq 0 ::: dq 0 : fds - proto (0, 30, 30) : hb (2, 2, 0) : fab (20, 20, 0)
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4614)    heartbeat_received: self 0 : foreign 102226
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4615)    heartbeat_stats: bt 0 bf 81744 nt 0 ni 0 nn 0 nnir 0 nal 0 sf1 0 sf2 0 sf3 0 sf4 0 sf5 0 sf6 0 mrf 0 eh 0 efd 0 efa 0 um 0 mcf 0 rc 0 
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4628)    tree_counts: nsup 0 scan 0 batch 0 dup 0 wprocess 0 migrx 0 migtx 0 ssdr 0 ssdw 0 rw 0
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4644) namespace test: disk inuse: 0 memory inuse: 150 (bytes) sindex memory inuse: 0 (bytes) avail pct 100
Mar 11 2015 12:27:55 GMT: INFO (info): (thr_info.c::4689)    partitions: actual 2062 sync 2034 desync 0 zombie 0 wait 0 absent 0
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: reads (0 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: writes_master (1 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::163)  (11: 0000000001)
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: proxy (0 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: writes_reply (0 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: udf (0 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: query (0 total) msec
Mar 11 2015 12:27:55 GMT: INFO (info): (hist.c::137) histogram dump: query_rec_count (0 total) count
```

After another 10 minutes of inactivity over fabric, some of the TCP connections have finally disappeared: 
```
as01
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39940      ESTABLISHED 24883/asd       
tcp        0      0 10.240.136.123:3001     10.240.135.8:39939      ESTABLISHED 24883/asd
```

```
as02
netstat -anp |grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45751    ESTABLISHED 24249/asd       
tcp        0      0 10.240.135.8:3001       10.240.136.123:45752    ESTABLISHED 24249/asd   
```

And, after a few further errors, new connections are established and writes start succeeding. 

What might be complicating things is the mechanism for how Google close TCP connections. However there are two probable solutions, either sending heartbeats over the socket, or Aerospike maintaining its idle fabric connections.

**Comment by psi-mankoski** [comment]
Thank you for the detailed comments! They're extremely helpful.

We've had some internal engineering discussions related to this issue, and we're looking deeper into the best solution. We'll keep you in the loop.

**Comment by psi-mankoski** [comment]
To bring this open issue up to date with the behind-the-scenes investigations, we have found that the behavior described in this issue is rooted in the GCE firewall rules. We have found that if the default permissive GCE-internal firewall rule is replaced with "tcp:3000-3004,32768-61000", i.e., permitting both the default required Aerospike server TCP ports, as well as the default ephemeral TCP port range, the server cluster will function as expected. Without the ephemeral ports explicitly enabled, the observed behavior observed is that the GCE firewall blocks (not closes: no RST packet is sent) idle cluster-internal TCP connections (e.g., the fabric) after ~10 minutes.
Next, we are investigating implementing (configurable) keep-alives, as was originally proposed.

**Comment by psi-mankoski** [comment]
The option of sending keepalive packets on all Fabric TCP sockets has been added to the development system. Expect to see it in an upcoming release. Sending keepalives is enabled by default, and the parameters are changeable via the configuration file.

**Comment by psi-mankoski** [comment]
FYI, the keepalive code has been released with Aerospike Server Community Edition version 3.5.12,
in a commit on 24 April 2015 entitled "AER-3541 - Need Method to Handle Networks That Actively Block Idle TCP Sockets".
(View using: "git log -p --grep=AER-3541".)
