### ISSUE TITLE
Unable to insert floating point number

### ISSUE THREAD

**Issue by dhanasekaran1980** [aerospike/aerospike-server#47]
I am trying to insert a Floating point number to a aerospike bin using python client.  The bin doesnt seem to be appear even on aql prompt.
Aerospike: 3.5.4
Python Client: 1.0.38

**Comment by psi-mankoski** [comment]
Thanks for the report. Floating point is not a [basic type](http://www.aerospike.com/docs/guide/data-types.html#basic-types) supported by the database , but rather would be handled as a [native format] (http://www.aerospike.com/docs/guide/data-types.html#native-formats) by the Python client. Could you therefore please enter this issue against the [Python client](https://github.com/aerospike/aerospike-client-python/issues)? Thanks!

**Comment by dhanasekaran1980** [comment]
Thanks a lot mankoski.  Ronen Botzer responded with the new python client release 1.0.40 which handles floating point numbers.  Thanks a lot to Ronen and Aerospike team.
