### ISSUE TITLE
Support of unix domain sockets

### ISSUE THREAD

**Issue by WhiteTrashLord** [aerospike/aerospike-server#49]
It seems that Aerospike currently only supports connections via TCP. Redis supports TCP/IP loopback and unix domain sockets. Maybe you can do the same?

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.

**Comment by bbulkow** [comment]
Running an aerospike server locally to your application in a single server doesn't make a lot of sense. If you need a ram cache, why not call malloc()? If you need persistence, why not use a local data storage library, like berkeleydb ?
