### ISSUE TITLE
Clarification about truncation with specific LUT

### ISSUE THREAD

**Issue by kennykarnama** [aerospike/aerospike-server#49]
**OS:** *Put your operating system here. For example: "Ubuntu 18.04 LTS", "CentOS 7", "Debian 9" etc.*

**Aerospike version:** *Put your Aerospike release version or `git describe --long --all` output here. For example: "3.15.0.1, heads/master-0-g450aee1"*

Aerospike CE Docker version 5.6.0.3

**Client version:** *Put which client and the version of the client you are using (if applicable) here. For example: "Java 4.0.8, C 4.2.0"

Go v4.5+
__________

*Explain your _Aerospike Server_ issue in detail here and (if applicable) provide logs snippets, configuration, and/or reproduction instructions.*

A bit confused with truncate using specific LUT

I tried to specify LUT in Go i.e.

```
time.Now().Add(3 * time.Second)
```

It doesn't truncate anything.

From log it was written like this

```
command lut 1680540851534065369 (Apr 03 2023 16:54:11 GMT) is in the future
```

Checked in truncate.c, apparently LUT cannot > now ?

https://github.com/aerospike/aerospike-server/blob/master/as/src/base/truncate.c#L182

**Comment by kportertx** [comment]
Correct, truncations are expected to either be now (default) or last updated some time in the past.
