### ISSUE TITLE
Permission denied while access to /dev/bcache0 device

### ISSUE THREAD

**Issue by AlexLov** [aerospike/aerospike-server#52]
Hi,
I'm trying to run aerospike server under aerospike user/group 
service {
    user aerospike
    group aerospike
}

But seems it can't access to /dev/bcache0 device even if user aerospike added to 'disk' group.
~# ls -l /dev/bcache0
brw-rw---- 1 root disk 251, 0 Mar 30 17:57 /dev/bcache0
~# id aerospike
uid=999(aerospike) gid=9071(aerospike) groups=9071(aerospike),6(disk)

When I change group to 'disk' in aerospike.conf, aerospike-server started without problem.

Is it expected behavior or I miss something?

OS: ubuntu 12.04
Kernel: 3.13.0-48-generic
aerospike-server-community: 3.5.4

aerospike.conf — https://gist.github.com/AlexLov/1bc1f602c3f460cf06d4
aerospike.log — https://gist.github.com/AlexLov/951c975dfede94bf217b

**Comment by wchu-citrusleaf** [comment]
Please see:
http://www.aerospike.com/docs/operations/configure/non_root/#configure-ssd-resources-used-by-namespace
