### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by killersteps** [aerospike/aerospike-server#52]
I wonder if it is possible to compile a tar.gz version for macOS? Including Intel and M chips, for local development and testing
This is a very cool thing for users who don't want to use Docker.

**Comment by killersteps** [comment]
Adding to the current situation, it is very frustrating.
**_error: darwin is not supported._**

**Comment by kportertx** [comment]
The server has quite a few dependencies on linux such as epoll and futex.

**Comment by killersteps** [comment]
> The server has quite a few dependencies on linux such as epoll and futex.

MacOS also has kqueue, similar to Netty, which can be well compatible with frameworks. Why is this difficult on Aerospike? Well, I have to run a Docker for this middleware alone -, -
This does add some additional costs and requirements

**Comment by rbotzer** [comment]
While it's a good feature request, to do this properly we'll need to add significant testing resources for an environment that is considerably different than 64-bit Linux OS flavors.

Thank you for the suggestion. We'll keep this in mind for the future.
