### ISSUE TITLE
client.operate - AEROSPIKE_ERR_REQUEST_INVALID

### ISSUE THREAD

**Issue by catroot** [aerospike/aerospike-server#53]
The examle code from http://www.aerospike.com/apidocs/python/client.html#id1
with an operate(key, list[, meta[, policy]]) -> (key, meta, bins)
Throws an error on this stage:
        {
          "op" : aerospike.OPERATOR_APPEND,
          "bin": "name",
          "val": ":end:"
        },

Prepend works fine, but append fails with error 
error: (4L, 'AEROSPIKE_ERR_REQUEST_INVALID', 'src/main/aerospike/as_command.c', 915)

Why aerospike wont append?
Is there a limit for one list `operate` to contain an APPEND and PREPEND operators for the same bin name?

Trying to rename bin name for APPEND to different one - works fine.
If names are the same for APPEND and PREPEND - operate fails.

Is that ok?

P.S. and there in example code 
   (key, meta, bins) = self.client.operate(key, list, policy={'timeout':500})
must be 
   (key, meta, bins) = client.operate(key, list, policy={'timeout':500})
i.e. without reference to self.

**Comment by rbotzer** [comment]
Yes, I can confirm that multiple write operations on the same bin throw that error. Moved the bug to the Python client's repo: https://github.com/aerospike/aerospike-client-python/issues/46

**Comment by wchu-citrusleaf** [comment]
Currently multiple "operation" on the same bin is not supported. We are looking at supporting it soon.

**Comment by wchu-citrusleaf** [comment]
multiple operations on the same bin is now supported, starting from 3.6.0
