### ISSUE TITLE
Configurable Graphite prefix in asgraphite

### ISSUE THREAD

**Issue by kennethjor** [aerospike/aerospike-server#55]
I don't know if this is the correct place to request this, but it would be nice to be able to configure the prefix `asgraphite` uses to transmit its stats. Currently they come in under `instances.citrusleaf`. Primarily we'd like to separate our dev and prod servers easily and replace that string with something like `aerospike.dev`, followed by the existing host name.

**Comment by kportertx** [comment]
I just published a repo here: https://github.com/aerospike/aerospike-graphite/tree/master
