### ISSUE TITLE
citrusleaf.py not in your python path. Set PYTHONPATH!

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-server#56]
With the last version (3.5.5), the PYTHONPATH is not set correctly on ubuntu.

Error during dpkg : Failed to parse python sys.path

Works well with previous version.

**Comment by bpaquet** [comment]
There are no *sites-packages on ubuntu, only dist-packages

**Comment by tuxinaut** [comment]
Same here :+1:

**Comment by nakulgan** [comment]
:+1:

**Comment by cqeescalona** [comment]
Same here

**Comment by swamysam** [comment]
Seeing the same issue.

**Comment by wchu-citrusleaf** [comment]
Thanks for the feedback. Will be taking a look.

**Comment by psi-mankoski** [comment]
Fix committed for inclusion in the next release.

**Comment by cqeescalona** [comment]
Thanks
