### ISSUE TITLE
Linux tar.gz package is not consistent with other distros

### ISSUE THREAD

**Issue by ultrabug** [aerospike/aerospike-server#57]
Hi,

While packaging Aerospike for Gentoo Linux [1] I found that the basic Linux tarball lacks a lot of files compared to its Debian et al counterparts [2].

Could we discuss the why and how to improve this since for now I'm forced to use the .deb package to get some real and usable content and tools ?

[1] https://gitweb.gentoo.org/dev/ultrabug.git/tree/dev-db/aerospike-server-community
[2] http://www.aerospike.com/download/server/

**Comment by cstivers78** [comment]
Thanks for the feedback. 

The Linux tarball was designed to be a self contained environment for running the server, without needing it to be installed on the system. We found it helpful for developers who do to quickly extract and run the server. 

However, I see your point. Its current design makes it difficult operators to install the software on servers. We may need to consider providing a binary package which extracts the files into a root (user-defined) directory. This is trivial, since it will be a copy of what we do for the rpm and deb packaging. 

The more difficult part is deciding how to label these two distributions for those trying to decide what to download. Maybe the current Linux tarball can be called "Quick Start" or similar.

If you would like to help out, it would be great if you could kick off the development of this new binary package, and have it live in "pkg/binary" (can always be renamed). It think it would look similar to the "pkg/deb" directory, except the actual "package" target would run "tar" instead of "dpkg-deb". Once you submit the pull request, we will take a look and give it a spin.

**Comment by ultrabug** [comment]
> We may need to consider providing a binary package which extracts the files into a root (user-defined) directory. This is trivial, since it will be a copy of what we do for the rpm and deb packaging. 

That sounds a fine idea for binary-based distributions such as Arch Linux.

> The more difficult part is deciding how to label these two distributions for those trying to decide what to download. Maybe the current Linux tarball can be called "Quick Start" or similar.

Yes, or "Standalone" maybe too ?

> If you would like to help out, it would be great if you could kick off the development of this new binary package, and have it live in "pkg/binary" (can always be renamed).

That's where, as a Gentoo dev, I have to say that I cannot endorse a binary distribution of Aerospike since it's against our policy. That's why I'm not satisfied with the current packaging I've been forced to do at the moment (but it helped me get acquainted to the sources tree).

I will thus focus on trying to have Aerospike server built from the sources and I guess I'll open another issue related to this since I already have a few QA blocker points in mind which I find quick to drop here :
- The sources use GIT submodules which makes the github tag & tarball of the main source repository impossible to checksum properly
- The sources do NOT respect user defined CFLAGS/CXXFLAGS/LDFLAGS and hard force them in the building process
- The sources make extensive use of bundled libraries and do not provide any flag to use system-wide libs instead
- I surely must search more, but I was unable to find where the tools such aql come from and why they have a different version from the main server
- Better respect the FHS

I hope we can work in an efficient a constructive manner to resolve those issues mate.

**Comment by ultrabug** [comment]
As referenced above I've proposed a first step fix to the build system to allow usage of system-provided jemalloc and jansson libs.

I managed to get rid of the debian packaging and my current ebuild [1] (gentoo install script) now build asd from sources which is a nice step. I get the following directory tree :

```
/etc
/etc/aerospike
/etc/aerospike/aerospike.conf
/etc/aerospike/aerospike_mesh.conf
/etc/aerospike/aerospike_ssd.conf
/etc/init.d
/etc/init.d/aerospike
/etc/logrotate.d
/etc/logrotate.d/aerospike
/opt
/opt/aerospike
/opt/aerospike/bin
/opt/aerospike/bin/afterburner.sh
/opt/aerospike/sys
/opt/aerospike/sys/udf
/opt/aerospike/sys/udf/lua
/opt/aerospike/sys/udf/lua/aerospike.lua
/opt/aerospike/sys/udf/lua/as.lua
/opt/aerospike/sys/udf/lua/external
/opt/aerospike/sys/udf/lua/external/llist.lua
/opt/aerospike/sys/udf/lua/external/lmap.lua
/opt/aerospike/sys/udf/lua/external/lset.lua
/opt/aerospike/sys/udf/lua/external/lstack.lua
/opt/aerospike/sys/udf/lua/external/validate_all
/opt/aerospike/sys/udf/lua/ldt
/opt/aerospike/sys/udf/lua/ldt/CRC32.lua
/opt/aerospike/sys/udf/lua/ldt/ldt_common.lua
/opt/aerospike/sys/udf/lua/ldt/ldt_errors.lua
/opt/aerospike/sys/udf/lua/ldt/lib_llist.lua
/opt/aerospike/sys/udf/lua/ldt/lib_lmap.lua
/opt/aerospike/sys/udf/lua/ldt/lib_lset.lua
/opt/aerospike/sys/udf/lua/ldt/lib_lstack.lua
/opt/aerospike/sys/udf/lua/ldt/validate_all
/opt/aerospike/sys/udf/lua/ldt/validate_lua
/opt/aerospike/sys/udf/lua/stream_ops.lua
/opt/aerospike/usr
/opt/aerospike/usr/udf
/opt/aerospike/usr/udf/lua
/opt/aerospike/usr/udf/lua/.keep_dev-db_aerospike-server-community-0
/usr
/usr/bin
/usr/bin/asd
/var
/var/log
/var/log/aerospike
/var/log/aerospike/.keep_dev-db_aerospike-server-community-0
```

Which still leaves this question open plz :

> I was unable to find where the tools such aql come from and why they have a different version from the main server

[1] https://gitweb.gentoo.org/dev/ultrabug.git/tree/dev-db/aerospike-server-community/aerospike-server-community-3.5.8-r1.ebuild

**Comment by wchu-citrusleaf** [comment]
Re: aql tools.
The aerospike-tools package bundled together with the official server bundles, do have the same versions (see http://www.aerospike.com/download/server/3.5.9/)

We have now separated out the tools package. They can be downloaded http://www.aerospike.com/download/tools/3.5.9/

**Comment by ultrabug** [comment]
This is good news @wchu-citrusleaf thank you. But you're closing this issue a bit fast imo :
- this does not really covers the main tar.gz linux package problem reported here
- the tools packaging does **not** offer a tar.gz generic archive so we're still stuck with .deb

Could we work on this please ?

**Comment by bbulkow** [comment]
Hi Ultrabug,
We'd like to not put further effort into improving the particular binary package you're really interested in (the other issue you reported). We'd like to focus on your effort to improve our build from source. How does that sound?

**Comment by ultrabug** [comment]
@bbulkow sounds even better of course, cheers !
