### ISSUE TITLE
cant compile on FreeBSD

### ISSUE THREAD

**Issue by sparvu** [aerospike/aerospike-server#59]
Is aerospike-sever a Linux only product ? I have tried to compile your server on FreeBSD:

```
$ make
make: "make_in/make_in/Makefile.vars" line 20: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 21: Need an operator
make: "make_in/make_in/Makefile.vars" line 22: Need an operator
make: "make_in/make_in/Makefile.vars" line 30: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 32: Need an operator
make: "make_in/make_in/Makefile.vars" line 67: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 69: Need an operator
make: "make_in/make_in/Makefile.vars" line 74: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 76: Need an operator
make: "make_in/make_in/Makefile.vars" line 81: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 83: Need an operator
make: "make_in/make_in/Makefile.vars" line 86: Missing dependency operator
make: "make_in/make_in/Makefile.vars" line 88: Need an operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 53: Missing dependency operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 55: Need an operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 56: Missing dependency operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 57: warning: duplicate script for target "ifeq" ignored
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 54: warning: using previous script for "ifeq" defined here
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 58: Need an operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 59: Missing dependency operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 60: warning: duplicate script for target "ifeq" ignored
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 54: warning: using previous script for "ifeq" defined here
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 60: warning: duplicate script for target "(1,1)" ignored
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 57: warning: using previous script for "(1,1)" defined here
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 61: Need an operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 183: warning: duplicate script for target "/configure" ignored
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 177: warning: using previous script for "/configure" defined here
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 186: warning: duplicate script for target "/Makefile" ignored
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 180: warning: using previous script for "/Makefile" defined here
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 206: Missing dependency operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 207: Need an operator
make: "/home/sparvu/workspace/aerospike-server/Makefile" line 208: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /home/sparvu/workspace/aerospike-server
-- 22:11 sparvu ~/workspace/aerospike-server --                          
```

or using gmake:

```
$ gmake
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
gmake: arch: Command not found
mkdir -p ./target/FreeBSD-/gen ./target/FreeBSD-/lib ./target/FreeBSD-/bin
mkdir -p ./target/FreeBSD-/m4/base ./target/FreeBSD-/m4/fabric ./target/FreeBSD-/m4/storage
mkdir -p ./target/FreeBSD-/obj/base ./target/FreeBSD-/obj/fabric ./target/FreeBSD-/obj/storage
gmake: arch: Command not found
build/gen_version community > ./target/FreeBSD-/gen/version.c
/bin/sh: build/gen_version: not found
Makefile:145: recipe for target 'target/FreeBSD-/gen/version.c' failed
gmake: *** [target/FreeBSD-/gen/version.c] Error 127
-- 22:11 sparvu ~/workspace/aerospike-server --      
```

**Comment by psi-mankoski** [comment]
Yes, currently the Aerospike server is designed, tested, and maintained to build on a specific set of Linux distributions, as listed in the main "README.md" file. When we can, we have made the necessary changes to extend the list of officially-supported platforms to include similar, popular distros.
That being said, we would accept input from the community for supporting additional platforms. Some of the changes may be relatively minor (e.g., finding an appropriate replacement for the "arch" command, which simply outputs "x86_64" on the currently-supported 64-bit Intel and AMD x86-based Linux platforms), while others may be architectural (e.g., we are heavily using Linux's "epoll", which may be provided in FreeBSD by a Linux emulation layer; Adding support for alternatively using FreeBSD's "kqueue" natively would be a much more serious effort.)
Comments? Thanks.

**Comment by sparvu** [comment]
I think, it would have been smarter to design the core server on at least *BSD and Linux operating systems. Not something only targeting Linux. 

Right, you need to look into kqueue to make it on FreeBSD. We are running on Redis and we are happy but some of our developers asked if we could consider Aerospike. For us FreeBSD would be mandatory requirement.

**Comment by bbulkow** [comment]
sparvu, one of the secrets to aerospike is it is not generic - it is tuned to the operating system. We originally started the project on freebsd because of kevent. With kevent, you get a unified notification system for storage and objects. That is a completely different code design - the threading model is different.

We moved from FreeBSD to Linux on the day that we found Valgrind wasn't supported anymore in FreeBSD. Valgrind is a key tool, and if the FreeBSD community was so small that Valgrind wouldn't support it, then we would find few people who would run FreeBSD. And, I have found in my history that the OS with the most users gets the most optimizations everywhere. For example, Intel's newest optimizations for the TCP stack are done only in Linux, too.

In any case, the Aerospike code is out there, and if you'd like to either create a FreeBSD fork which you think might be minimal, we'd love to see it. We probably wouldn't ever accept it into our branch, though, because spooling up testing ( we test on a 100 node cluster for weeks before pushing open source changes ) is a huge amount of work.

**Comment by vlsergey** [comment]
would like to see it for FreeBSD as well, so +1 from me

**Comment by kabu4i** [comment]
+1 for FreeBSD.
Almost latest Valgrind version 3.10 is living in ports.

**Comment by MaxJust** [comment]
+1 for FreeBSD

**Comment by lewpayne** [comment]
+1 for FreeBSD - at least 1 of the 2 companies I'm involved with (as board member and CTO) will be needing its scalability toward the end of 2016.  Commercial customers - enterprise accounts.

**Comment by mzs114** [comment]
I will need this to consider Aerospike over others like Cassandra, Mongo, which work on FreeBSD.
We currently have time sensitive applications on them.

**Comment by weiishann** [comment]
+1 for FreeBSD

**Comment by bbulkow** [comment]
Are any of you interested in doing the port? We're interested in reviewing it and pulling it into mainline.
