### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [aerospike/aerospike-server#6]
I suggest to add the key word "const" to the type specifiers for parameters like the following.
* tname (functions "[ai_create_table](https://github.com/aerospike/aerospike-server/blob/54668b9a0e7d2423ea41b225de780fbbdd8362e4/ai/include/ai.h#L43)", "[find_table](https://github.com/aerospike/aerospike-server/blob/17260c57f812e02b9529d03fae9304f41561165e/ai/include/find.h#L59)")
* akey (function "[bt_exist](https://github.com/aerospike/aerospike-server/blob/54668b9a0e7d2423ea41b225de780fbbdd8362e4/ai/include/btree.h#L85)")

Would you like to apply the advices from [an article](http://en.wikipedia.org/wiki/Const-correctness "const-correctness") to more places in your source files?

**Comment by psi-mankoski** [comment]
Thanks for the suggestion. True "const" correctness would be nice to have throughout the code, but honestly it's not currently as high on our list as other improvements. If you can point out any places where the lack of "const" correctness has an externally-visible effect on program behavior, however, that would be a big help.
