### ISSUE TITLE
how to failover by simple slave promotion

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#61]
I hava a aerospike cluster of 2 replica.

When a node failed, the aerospike make failover by auto-rebalance. 

In some database systems (like redis),  by simpely promoting some slaveswhose corresponding master is failed to master, the cluster will still be healthy for all partitions despite some partitions have only master and no slaves. I think this way is much more lightweight. So, in aerospike, can I configure to fail over in this simple way?

**Comment by wchu-citrusleaf** [comment]
This, is in reality what happens with Aerospike's automatic re-balance algorithm as well.

When a node departs, one of the following 3 conditions may be true about each of the (4k) partitions in the system:

(1) The departed node is neither the master nor replica of the partition. Thus, no movement of the data in this partition. Client traffic to master unchanged.
(2) The departed node is the replica for the partition. Thus, master will start replicating to the newly assigned replica owner. Client traffic to master also unchanged.
(3)  The departed node is the master for the partition. The replica node is immediately assigned to be the master of the partition. Client will switch over to talk with the new master. New master will start replicating to a new replica owner.

**Comment by billbargens** [comment]
OK, got it! Thank you for your detailed explanation!

**Comment by billbargens** [comment]
Can I configure to make no rebalance/migration when fail over? That means : When the departed node is the master for the partition, the replica node is immediately assigned to be the master of the partition. Client will switch over to talk with the new master. But New master will not start replicating to a new replica owner.

**Comment by wchu-citrusleaf** [comment]
Replication will happen automatically. There is no configurations associated with re-balancing. Thus the simplicity of the system.
