### ISSUE TITLE
Large Data Types find function with offset

### ISSUE THREAD

**Issue by WhiteTrashLord** [aerospike/aerospike-server#63]
I just checked the documentation of Large Data Types. In Java you have this function:

findFirst(int count)
Select values from the beginning of list up to a maximum count.

I miss a function like find(int offset, int count) to navigate through the list without knowing any values.
Or is there a better way for this use case?

**Comment by citrusraj** [comment]
There is no notion of offset but there is notion of from. You could findFrom(startkey, int count). This should give fairly good approximation of offset give LLIST is list of unique keys.

-- R

**Comment by WhiteTrashLord** [comment]
I also saw this function. But it's not a big help. As I already wrote: I want to navigate without setting any keys. In other words: I want something like the LIMIT statement in SQL. I am sure that many people need something like this for Large Data Types.
