### ISSUE TITLE
Can I install and run aerospike server on  CentOS5.5?

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#64]

**Comment by wchu-citrusleaf** [comment]
We have dropped official support of CentOS5 given the low demand. However, the previous versions of Aerospike ran on centOS5 in large scale. Definitely recommend trying to build and run on a centOS5.

**Comment by billbargens** [comment]
So which version is your recommendation on CentOS5 ?

**Comment by wchu-citrusleaf** [comment]
Best to move to centOS6. Please see supported platforms:
http://www.aerospike.com/download/server/

**Comment by billbargens** [comment]
I have some servers with CentOS5 but I don't have the privilege to change the os. 
I want to make some tests at first.
So which old version do you recommend to run aerospike cluster?

**Comment by wchu-citrusleaf** [comment]
We do not recommend the old version of the community build. It is more restrictive in number of nodes and size. Your best path forward is try a build from source on a centOS5 machine. Thanks.

**Comment by shatil** [comment]
@billbargens, I'm not familiar at all with building Aerospike, but if they've required newer packages in their toolchain than CentOS 5 supports, `devtoolset` might come to your rescue: http://linux.web.cern.ch/linux/devtoolset/
