### ISSUE TITLE
Bluemix Integration?

### ISSUE THREAD

**Issue by lukeadams** [aerospike/aerospike-server#65]
I think Aerospike should contact IBM to make it simpler for users to deploy apps in Bluemix. Currently the only option is to deploy the docker container to IBM's experimental container infrastructure. 
Not sure how feasible it is to get it on Bluemix.
Here's where to contact IBM: http://www.ibm.com/marketplace/cloud/us/en-us
What do you think?

**Comment by bbulkow** [comment]
Hi Luke,

Love your logo. 

We've prioritized EC2 first, Google second, Azure third, BlueMix/Softlayer and Rackspace next. It takes time to work through all the types and give guidance on performance. It often takes us literally months to have our hardware recommentations.

If you're available to help us, or know an open source developer we can support, please reach out to me directly: brian@aerospike.com .

**Comment by Mouvedia** [comment]
:+1:

**Comment by lukeadams** [comment]
Just if anybody is currently "trying" to use it with Bluemix: you can deploy Aerospike as a docker container on IBM Containers Engine (I think BM even lets you bind ports to your CF apps).
Anyways, just a heads up since Docker on BM is now out of testing. 
(Although admittedly you do have to run your own cluster...)

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
