### ISSUE TITLE
Install: Binary Package vs Rpm Package

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#66]
I hava found two methods to install and run aerospike server in the official document:
1. with rpm package: http://www.aerospike.com/docs/operations/install/linux/el6/
2. with binary package: http://www.aerospike.com/docs/operations/install/linux/other/

Does the first method have some pros over the second method? 
And can I use the second method to start and run aerospike server in production environment or it is just for test?

**Comment by bbulkow** [comment]
The binary package works in cases where you are not on a RPM or DPKG maintained system, and it runs in an arbitrary directory instead of taking over system directories. It's easier to get the binary package working without 'sudo' privs.

**Comment by billbargens** [comment]
You mean I can use the binary package to start and run aerospike server in production environment?

**Comment by bbulkow** [comment]
It's the same binary software as in the RPM. 

Although we intend the binary package for programmers and developers who want a quick untar-and-run experience, you can do whatever you like. it's open source. If you'd like our professional opinion as a company that's supported and maintained hundreds of large scale deployments, we'd say you should use our Enterprise version, which we support to the hilt.

RPM has advantages for a production environment. I personally wouldn't recommend to a friend using a non-package-manager approach on production systems in the linux environment of any software, but you know your environment & pressures, I don't. Maybe it's right for you.

**Comment by billbargens** [comment]
When I use rpm installation, how to run multiple aerospike server instances on one machine with different conf file?

**Comment by bbulkow** [comment]
Aerospike's RPM installation doesn't do that. RPM, generally, is very bad at that sort of thing. If you want or need multiple servers (like for testing clustering), the binary package is better because you can create different directories, each with their own conf file. You can also test things like having different versions in the same cluster with one physical machine --- that's how some of our internal test scripts work. We're flipping some of that stuff over to docker.

Why would you run multiple copies on the same physical machine in a production system?

**Comment by billbargens** [comment]
When I want to add namespaces, I must modify the conf and restart the server.
I think that‘s bad!
My intended solution for this is to start a new server instance to deploy the new namespace on the same machine.

**Comment by bbulkow** [comment]
You should use sets instead of namespaces. They are dynamic. 

We will eventually make namespaces dynamic as well, but it's rare to add hardware capacity to a machine.

You should add namespaces only when you add or remove hardware from a server.

**Comment by billbargens** [comment]
I want to add namespace because I want to store new data on disk instead of memory as the existing namespace do.

**Comment by ultrabug** [comment]
I'd like to take the opportunity to raise again the issue #57 and especially @cstivers78 acknowledgement (first comment) about the tar.gz package usage / limitations. Looks like this could also benefit to this issue here.
