### ISSUE TITLE
Debian init script is missing start/stop levels

### ISSUE THREAD

**Issue by b-a-t** [aerospike/aerospike-server#68]
Hi!

Debian init script is missing start/stop default levels, so adding package to the system gives a warning  and AS doesn't start on reboot unless you take additional measures.

I'd suggest to add to the https://github.com/aerospike/aerospike-server/tree/master/as/etc/init-script.deb the following snippet:
```
### BEGIN INIT INFO
# Provides:             asd
# Required-Start:       $remote_fs $network
# Required-Stop:        $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Aerospike Clustered Data Service
### END INIT INFO
```
This is what I replace default init script with on every install. Oh, and I see similar issue for RH in #35

**Comment by wchu-citrusleaf** [comment]
Thanks. We will look into testing this in various platforms.

**Comment by psi-mankoski** [comment]
Fixed in the development mainline.
