### ISSUE TITLE
Aerospike Forum is unavailable

### ISSUE THREAD

**Issue by KayGuoWhu** [aerospike/aerospike-server#69]
Aerospike Forum(https://discuss.aerospike.com/) is unavailable for months. 

This Issue is the most direct way to report the problem because I couldn't find other 'Internet' contact details on the official website.

I am looking forward to your replay. My email is guokaiwhu at gmail dot com. Thank you! :)

**Comment by bbulkow** [comment]
KayGuoWhu, the discuss site has been fully available during this time.
If you are trying from China, we believe it is likely the Chinese government has censored our site, although we don't know why.

At Aerospike, we do not condone breaking any national laws, so you should check to see if accessing Aerospike forums is legal. If these sites are being blocked in error, you will have to take that issue up with those who are blocking.

If you wish to purchase enterprise support, support is available via phone and email 24/7.

**Comment by KayGuoWhu** [comment]
@bbulkow Thanks for your helpful solution. It is the GFW (Great Fire Wall) that blocks the website.
