### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [aerospike/aerospike-server#7]
I guess that a different program design will be needed for your function "[as_sig_handle_term](https://github.com/aerospike/aerospike-server/blob/17260c57f812e02b9529d03fae9304f41561165e/as/src/base/signal.c#L52)".
- The variable "g_startup_complete" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers).
- The functions "[cf_fault_event](https://github.com/aerospike/aerospike-server/blob/17260c57f812e02b9529d03fae9304f41561165e/cf/include/fault.h#L173)" and "[pthread_mutex_unlock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_unlock.html)" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).

**Comment by psi-mankoski** [comment]
Thanks for the feedback. We'll look into fixing this.

**Comment by kportertx** [comment]
I'm not convinced changing this is worthwhile, but open to discussion.

Thanks.

**Comment by elfring** [comment]
I would appreciate if you would [care more](https://github.com/aerospike/aerospike-server/blob/3476e13126ea18f1d36462e2b51728225a0b5b51/as/src/base/signal.c#L87 "Check signal handling") for [the development topic “async-signal-safety”](https://stackoverflow.com/questions/8493095/what-constitutes-asynchronous-safeness "What constitutes asynchronous-safeness?").

**Comment by kportertx** [comment]
First, cf_fault_event is part of this code base, so it wouldn't be on that list. It does call the printf family so we risk interleaved text on signals in the logs. This isn't a big concern.

Second, using pthread_mutex_unlock alone should be safe. The concern for async safety is that the signal handler is using locks to enter a protected region where it can be interrupted by a new signal causing a deadlock. This code unconditionally unlocks (never locking) a lock on certain signals to allow the main thread to exit. If these signals race with the main thread acquiring the lock, the server could fail to stop. This is only visible at initial startup and it can be resolved simply.

The sig_atomic_t type is defined to be int on x86, for portability we should use the sig_atomic_t type instead. This isn't a present concern. 

Lastly, I didn't say we didn't care about your concern. After evaluating the current code I didn't see a worthwhile reason to persue an alternative. If you are able to provide and describe a specific problem we would be happy to reevaluate.

**Comment by elfring** [comment]
Is it better to avoid mentioned risks for deadlocks?


Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)

**Comment by kportertx** [comment]
> Is it better to avoid mentioned risks for deadlocks?

I didn't mention a deadlock. I was saying that our usage won't deadlock. Also after a closer inspection to evaluate the potential for the server to fail to stop, that too wouldn't be possible. When the main thread acquires the g_main_deadlock it then sets g_startup_complete to true. The signal handler will call _exit(0) if g_startup_complete isn't true so Aerospike will always exit.

We would be happy to consider one of those solutions, could you describe the problem they are meant to solve in this code base? I don't think it is worthwhile to implement a solution that doesn't solve a problem.

**Comment by elfring** [comment]
>I was saying that our usage won't deadlock.

I suggest to take another look at your previous wording which indicates corresponding software risks.
* … It does call the printf family …
* … the signal handler is using locks …

**Comment by kportertx** [comment]
>  It does call the printf family

Again, it isn't worthwhile to complect this code to prevent printf logs from being garbled by signal races.

>  the signal handler is using locks

The full sentence is describing the concern for async saftey and locks. The following sentence describes our usage why it doesn't have this problem.

Please don't reraise this issue without identifying a worthwile problem that your solution solves.

**Comment by elfring** [comment]
>… printf logs from being garbled by signal races.

Such output should not be performed by a signal handler.


>… without identifying a worthwile problem …

It seems that you do not take async-signal-safety so serious then.
