### ISSUE TITLE
questions about partition Tolerance

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#70]
Assume: 
we have 5 server: A, B, C, D, E
The data is divided into 5 partitions (just for simple, although it is 4096 in fact): P1，P2， P3, P4, P5
The Cluster is start up with 2 replica.
Then, also assume the partitions come to such a distribution over the five servers: 

A: P1-MASTER,  P2-SLAVE
B: P2-MASTER,  P3-SLAVE
C: P3-MASTER,  P4-SLAVE
D: P4-MASTER,  P5-SLAVE
E: P5-MASTER,  P1-SLAVE

Also，the smart client of aerospike get the partition-map.

My question is: if the network partition happens, and assume the cluster is divided into two parts:
A,B,C and D,E.  what is the reaction of cluster servers and the client?

**Comment by billbargens** [comment]
Because there is four partitions(P1, P2, P3, P4) in the first-part servers(A,B,C), and  three partitions (P4, P5, P1) in the second-part servers(D,E), so I guess: the two parts will make auto-rebalance seprately and finally the first-part servers will hold 8 replicas for (P1, P2, P3, P4) and the second-part server will hold 6 replicas for (P4, P5, P1). 

Is it right?

**Comment by wchu-citrusleaf** [comment]
If the cluster cleanly splits, and two sub-clusters form cleanly, then yes each sub-cluster will have nodes change partition ownership, re-balance the partitions within, and eventually reach the state described above. This is not the likely situation in practice though. Mostly the case is a temporary network glitch, and certain nodes may temporarily form sub-islands for up to a few seconds, then quickly cluster form back together again with original partition ownerships.

**Comment by billbargens** [comment]
If the cluster cleanly splits described as above, what is the reaction of the client?

**Comment by wchu-citrusleaf** [comment]
Client, during its periodic-ping against the nodes, will see that the partition-generations on respective nodes changed, and refreshes its partition-map against the nodes. Since the nodes do not have a consistent view of partition ownership due to the cluster split, the nodes will not return the same map to the client, and the client will end with a mixture map of the two clusters.

The mixture map is used to route requests. Once the request reaches the server node,  the server node may decide to proxy the request, based on its (now split cluster) view of partition ownership.

**Comment by billbargens** [comment]
From the example above we know the cluster will split to two parts:
part one: (A,B,C) holds 8 replicas for (P1, P2, P3, P4)
part two: (D,E) holds 6 replicas for (P4, P5, P1).

so:
1. what does the mixture map like for P4 and P1? 
2. how will the client deal with the request whose key belongs to P4 or P1?

**Comment by wchu-citrusleaf** [comment]
On the 2 cleanly split cluster, the partition-map will be the same within each cluster.  
The mixture map is on the client side, depending on if its refresh cycle, may get either A or E as the owner of P4, and will go to that node for request.

**Comment by billbargens** [comment]
OK, thank you for your explanation in detail
