### ISSUE TITLE
code error in thr_info.c

### ISSUE THREAD

**Issue by KayGuoWhu** [aerospike/aerospike-server#71]
May be it is a code error when using pthread_create to share a common pthread_t.
The error line is as follow( aerospike-server/as/src/base/thr_info.c line 7158). 

![image](https://cloud.githubusercontent.com/assets/2885034/7956998/c4fd8506-0a16-11e5-9b99-f77ffbab2250.png)

**Comment by wchu-citrusleaf** [comment]
This is an issue indeed. Thanks for bringing it to our attention!

**Comment by wchu-citrusleaf** [comment]
In 3.6.0
https://github.com/aerospike/aerospike-server/commit/2a2bd48db9a874dcedae86b70b5b9076bbcd1363
