### ISSUE TITLE
What the original caused the Aerospike cluster TPS bottleneck？

### ISSUE THREAD

**Issue by DoubleYan** [aerospike/aerospike-server#72]
We use two mechine to build a  Aerospike cluster.
Mechine Hard Ware ：
CPU: Intel(R) Xeon(R) CPU E5-2650 
Memory: 64G
System : CentOS release 6.4 (Final)
Disk: Fusion ioDrive PCIe(2T)

This is out  Aerospike  server's conf。
service {
        user root
        group root
        paxos-single-replica-limit 1 # Number of nodes where the replica count is automatically reduced to 1.
        pidfile /var/run/aerospike/asd.pid
        service-threads 32
        transaction-queues 32
        transaction-threads-per-queue 3
        proto-fd-max 100000
        fabric-workers 96
}

logging {
        # Log file must be an absolute path.
        file /var/log/aerospike/aerospike.log {
                context any info
        }
}

network {
        service {
                address any
                port 3000
        }

        heartbeat {
                #mode multicast
                #address 239.1.99.222
                #port 9918

                # To use unicast-mesh heartbeats, remove the 3 lines above, and see
                # aerospike_mesh.conf for alternative.
                #
                mode mesh
                port 3002

                mesh-seed-address-port 192.168.1.116 3002

                mesh-seed-address-port 192.168.1.117 3002

                interval 150
                timeout 20
        }

        fabric {
                port 3001
        }

        info {
                port 3003
        }
}

namespace test {
        replication-factor 2
        memory-size 75G
        default-ttl 30d # 30 days, use 0 to never expire/evict.
        high-water-memory-pct 99        

        # Warning - legacy data in defined raw partition devices will be erased.
        # These partitions must not be mounted by the file system.
        storage-engine device {
                # Use one or more lines like those below with actual device paths.
                #device /dev/sdb1
                #device /dev/sdc1
                device  /dev/fioa
                # The 2 lines below optimize for SSD.
                scheduler-mode noop
                write-block-size 128K

                # Use the line below to store data in memory in addition to devices.
#               data-in-memory true
        }
}

we use Aerospike benchmark tools to test  Aerospike cluster's performance。
Aerospike cluster's  Read TPS bottleneck  is 40000（TPS）。 But mechine‘s load is very low。
What the original caused the Aerospike cluster TPS bottleneck？

**Comment by wchu-citrusleaf** [comment]
This is a tuning question. If you have bought Aerospike Enterprise, Aerospike support will be able to help. Otherwise, feel free to solicit experience from Aerospike Community Forum https://discuss.aerospike.com/
