### ISSUE TITLE
'Failed to seed cluster' after tweaking aerospike.conf for fresh installation

### ISSUE THREAD

**Issue by seenickcode** [aerospike/aerospike-server#74]
Hello, I'm installing Aerospike community 3.5 on Ubuntu 12.04. I then edit /etc/aerospike/aerospike.conf to add a namespace configuration, restart the server, then run aql (or aql localhost) and I'm getting the following error:

````
2015-06-04 16:04:18 WARN AEROSPIKE_ERR_CLIENT Socket write error: 111
Error -1: Failed to seed cluster
````

I also get this when reverting aerospike.conf back to its original state and restarting Aerospike.

Any ideas? Thank you.

**Comment by wchu-citrusleaf** [comment]
Usage issues are best answered on community, https://discuss.aerospike.com/

For this specific issue, please check if you are able to access port 3000 locally. Could be firewall/selinux issues.

**Comment by seenickcode** [comment]
Ok, posted here https://discuss.aerospike.com/t/error-1-failed-to-seed-cluster-when-using-aql-cli-tool/1344
