### ISSUE TITLE
Erlang client planned to be on github?

### ISSUE THREAD

**Issue by liveforeverx** [aerospike/aerospike-server#76]
Do not know, where to start an issue, I think, that it is a definitely wrong place, but want to question:

Are you planning to have erlang client on github?

**Comment by wchu-citrusleaf** [comment]
The erlang client's source code is included in the download package. Currently there is no plan to put on github.

**Comment by liveforeverx** [comment]
@wchu-citrusleaf I would like to contribute with support of secondary indexes to erlang client, if it were in github, it were easier.

**Comment by wchu-citrusleaf** [comment]
Thanks for the interest @liveforeverx! The Erlang client is built on top of an old, legacy C client which does not support secondary index, thus is not the correct basis for improvement of the Erlang client. And we currently do not have plans to migrate the Erlang client onto the current C client.

The best choices to improve Erlang support is to (1) build it on top of the open-sourced C client https://github.com/aerospike/aerospike-client-c, similar to our PHP and Python clients, or (2) Start a native Erlang client and implement the wire-protocol, similar to our Java, C#, Go clients.

**Comment by liveforeverx** [comment]
Is that wire-protocol actual documentation ( http://www.aerospike.com/docs/reference/wire-protocol/ ) ?

**Comment by wchu-citrusleaf** [comment]
Yes. However, the information here currently is quite limited. Only contains Key-value information
Looking at source code of Java/C#/Go will be more instructive.

**Comment by henry-hz** [comment]
@liveforeverx hi there, did you decide to build a new erlang client ? maybe I could help

**Comment by vegabook** [comment]
Seconded on erlang client. Elixir momentum is making this interesting. Wish i were a good enough coder to do this myself.

**Comment by santaux** [comment]
> Seconded on erlang client. Elixir momentum is making this interesting. Wish i were a good enough coder to do this myself.

It would be great if you do it. I think a lot of people waits for a new client...

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
