### ISSUE TITLE
CSV export in aql

### ISSUE THREAD

**Issue by kennethjor** [aerospike/aerospike-server#77]
I'd like to request the addition of an old-school standard CSV format export be added to `aql`. I know it supports "table" and "json" output, but the neither of them properly escapes the fields, making it somewhat difficult to work with. For instance json doesn't esacpe quotes in strings and table doesn't escape pipes in strings. Additionally the table format is padded at the ends.

By "standard CSV" I mean unpadded, comma separated, quoted CSV files. For instance the values:
1. `value 1`
2. `value "2"!`
3. `value,3`

would be exported as:

`"value 1","value ""2""!","value,3"`

**Comment by zerebral** [comment]
Created a patch to export the data from Aerospike in a CSV format. 
You could build this one - https://github.com/zerebral/aerospike-tools-backup
and execute it like asbackup - the output will be CSV format for the bins you specify. 

The command line parameters are the same as the asbackup utility. You'd need to specify the bins-list parameter to specify the order of fields that go in the CSV. 

e.g. ./bin/asbackup --host 10.68.77.46 --port 9917 --namespace zerebral --set listings --directory ./aerospike_backup/ -r --bin-list id,price,miles,heading,year,make,model --no-indexes

This patched asbackup utility also adds the headers in each CSV file it exports.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
