### ISSUE TITLE
Adding CP mode?

### ISSUE THREAD

**Issue by liveforeverx** [aerospike/aerospike-server#80]
Is it in your Roadmap(or development) to add CP-mode for database?

Is there some plans, where CP mode will be  available, in near future(half year) or in a faraway future may be in 3 or more years?? 

Question is because, to get information: only to get feeling if it priorized may be or have no priority at the moment, if it much work or not so much to add to actual state of aerospike.

**Comment by bbulkow** [comment]
It is in our roadmap.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
