### ISSUE TITLE
record udf bug

### ISSUE THREAD

**Issue by chzhuo** [aerospike/aerospike-server#82]
server version : Aerospike Community Edition build 3.5.14  

When execute a record udf function which have a string argument ,this server will crash.  
i also try other clients and aql,still have the bug.  

udf code:
```lua
function args_test_void(...)
    print("================================void")
end
```
server log:  
![image](https://cloud.githubusercontent.com/assets/10919124/9051996/6bede1fa-3a94-11e5-92d2-0122ab71f080.png)

aql code:  
![image](https://cloud.githubusercontent.com/assets/10919124/9052009/922ea502-3a94-11e5-92c4-5f6c33b81ee3.png)

java code:
```java
		AerospikeClient client = new AerospikeClient(null,"127.0.0.1", 3000);
		Key key = new Key("test","test_set_len",1);
		client.execute(null, key, "record_udf", "args_test_void", new StringValue("sadadsdsddssdssds"));
```

**Comment by wchu-citrusleaf** [comment]
will take a look

**Comment by bwhisler** [comment]
We are trying to reproduce the issue.  Which version of the java client are you using?

**Comment by chzhuo** [comment]
Java client:
<dependency>
	<groupId>com.aerospike</groupId>
	<artifactId>aerospike-client</artifactId>
	<version>3.1.3</version>
</dependency>

**Comment by wchu-citrusleaf** [comment]
The tests all succeeds well on centOS6 machine, with default lua-jit build.
Are you running in a different environment? Do you use a different lua version?

**Comment by chzhuo** [comment]
Sorry ,not Bug, I konw what's wrong!

**Comment by wchu-citrusleaf** [comment]
Glad to know it was not a bug. Would be great if you can share the insight for future users too. Thanks.

**Comment by chzhuo** [comment]
I wanna return byte array from stream udf, so i modify the modules/mod-lua/src/main/ mod_lua_val.c file to put byte array into a string,i forbid to cut the string by '\0'.
