### ISSUE TITLE
Record come back after aerospike restsart

### ISSUE THREAD

**Issue by MaxJust** [aerospike/aerospike-server#84]
Hi everybody, I have a question about deleting records and sets in aerospike. I using aql utility command: 
```
delete from broker.broker WHERE PK = 'key value'
```
and after executing this commands all looks fine:
```
aql> select *  from broker.broker
0 rows in set (0.022 secs)
```

But when I restart aerospike (service aerospike restart), I got this:
```
aql> select *  from broker.broker
+-------------+----------+
| key         | bin1     |
+-------------+----------+
| "key value" | "value1" |
+-------------+----------+
1 row in set (0.037 secs)

```

Why record is come back?  How can I remove record?

**Comment by wchu-citrusleaf** [comment]
Please see https://discuss.aerospike.com/t/expired-deleted-data-reappears-after-server-is-restarted/470
