### ISSUE TITLE
Support for range scan (prefix) for string primary/secondary index ?

### ISSUE THREAD

**Issue by kk00ss** [aerospike/aerospike-server#9]
Hello, great work, thank you for opensourcing it.
Could anybody suggest why aformentioned functionality is missing? Is it due small primary index key size or some other design considerations? 
WBR, Konstantin.

**Comment by kportertx** [comment]
We appreciate your feedback; however, at this time we would like to limit the issue tracker to Aerospike Server bug reports only. Please refer to the [Aerospike Forum](https://discuss.aerospike.com/) for other matters such as requests for help, feature requests, and enhancements.
