### ISSUE TITLE
the numbers of the master objects and the replica objects are not consistent

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#92]
I hava a aerospike cluster with two instances, 2 replicas, and ssd as storage, the conf is as fellow:

single-bin false
replication-factor 2
memory-size 20G
default-ttl 30d # 30 days, use 0 to never expire/evict.
write-commit-level-override all
storage-engine device {
    device /dev/sdc1
    write-block-size 1M
    data-in-memory false
    cold-start-empty true
} 

I ran a flow to import some versional data to the aerospike cluster every day(inserting new generated data and deleting expired data). 

At first, the number of the master objects and replica objects are equal and consistent with the actual dataset's size.

But after I ran the flow some times, only the number of master objects was consistent with the actual dataset's size. 

![image](https://cloud.githubusercontent.com/assets/6092788/9729790/96069ce0-5644-11e5-8a03-0eb7fd2cd06d.png)

Is this normal?

**Comment by billbargens** [comment]
I found a clue in http://www.aerospike.com/docs/guide/FAQ.html:
 
“Every record value is limited to 128 KB. This is not really a hard limit, but one imposed by the block size on SSD. We can theoretically increase this limit by increasing the limit, however this has not been fully tested.”

The value in my data is larger than 128K

Can somebody verify this guess?

**Comment by bbulkow** [comment]
The limit is actually 1M, that FAQ is in correct. AS often recommends 128K based on flash storage provider. 

Here's the doc area for setting / changing / validating the configuration.

http://www.aerospike.com/docs/operations/configure/namespace/storage/
