### ISSUE TITLE
Repeat if statement

### ISSUE THREAD

**Issue by KayGuoWhu** [aerospike/aerospike-server#94]
![aerospike-issue](https://cloud.githubusercontent.com/assets/2885034/9806489/9cb1bbee-5877-11e5-990c-f997ffd2b668.png)

As is shown in the graph, it is a code snippet in the file paxos.c.

When the if statement in line 2918 is true, the if statement in line 2919 is true(the variable already_sent_partition_sync_messages has been assigned in line 2909). So the else statement in line 2928 makes no sense. 

Indeed, the code in else statement in line 2928 is the must way to send sync messages to all nodes.

In my opinion, the if statement in line 2918 is redundant.

**Comment by psi-mankoski** [comment]
Thanks for your interest.
The code is a bit more subtle than in your analysis.
I'll leave it as a puzzle for you to figure out why.

**Comment by KayGuoWhu** [comment]
@psi-mankoski the variable“already_sent_partition_sync_messages” is intended for the node just departed. When principal processes its sync request message, if it has already sent partition sync messages to other nodes except the departed node, it will just send a partition sync message to the departed one other than all. 
Is it right? :question:

**Comment by psi-mankoski** [comment]
Yes!! That's right! So, given your revised analysis, do you still see any issues with the code?
Please let us know what problems you may find, and feel free to propose solutions / do pull requests with fixes. Thanks!!
