### ISSUE TITLE
Add proper logging message if cannot allocate more stages

### ISSUE THREAD

**Issue by alexandrnikitin** [aerospike/aerospike-server#98]
Here:
https://github.com/aerospike/aerospike-server/blob/9a80dee49517ef8a24d6b3b72b746a48bab08f33/cf/src/arenax_cold.c#L38

**Comment by ariane6** [comment]
Hi Alexandr, 

Appending your notifications on Twitter here to give provide more context to your reported issue: 
" One more unpleasant surprise from #aerospike 256GB memory size limit per node without documentation or error msg :(( "
"And I still don't see the RAM limitations in docs!"

We see your highlighted code, but the arenas we have set up are for internal bookkeeping; they don't constitute an external limitation.

Thus, you are assuming there is a RAM limitation per node, but there is not; and there are no documentation changes to make on our part.

If you've encountered an error when you've allocated more than 256GB of memory size, please send us the error message so we can work on your issue.
